import { SceneContext, SceneDesc, SceneGroup } from "../SceneBase";
import { GfxDevice } from "../gfx/platform/GfxPlatform";
import { SceneGfx } from "../viewer";

import { rust } from '../rustlib.js';
import { FFXIVFilesystem } from "./files/Filesystem";
import { SceneLoader } from "./sceneloader";
import { SceneNode } from "./scenegraph";
import { FFXivSceneRenderer } from "./render/render";

abstract class FFXIVSceneGraphDesc implements SceneDesc {
    constructor(public id: string, public name: string = id) {
    }

    async createScene(device: GfxDevice, context: SceneContext): Promise<SceneGfx> {
        rust.init_panic_hook();

        const fs = new FFXIVFilesystem(context.dataFetcher);

        console.time("Load FS");
        const sceneGraph = await this.createSceneGraph(fs);
        console.timeEnd("Load FS");

        return new FFXivSceneRenderer(device, fs, sceneGraph);
    }

    abstract createSceneGraph(fs: FFXIVFilesystem): Promise<SceneNode>
}

class FFXIVMapDesc extends FFXIVSceneGraphDesc {

    constructor(public override id: string, public override name: string = id) {
        super(id, name);
    }

    async createSceneGraph(fs: FFXIVFilesystem): Promise<SceneNode> {
        return await new SceneLoader(fs).loadLevel(this.id);
    }
}

class FFXIVSgbDesc extends FFXIVSceneGraphDesc {

    constructor(public override id: string, public override name: string = id) {
        super(id, name);
    }

    async createSceneGraph(fs: FFXIVFilesystem): Promise<SceneNode> {
        return await new SceneLoader(fs).createNodeFromGb(this.id, await fs.loadSgb(this.id));
    }
}

const sceneDescs = [
    "Debug",
    new FFXIVSgbDesc(`bgcommon/world/aet/shared/for_bg/sgbg_w_aet_001_01a.sgb`, "Limsa Aetheryte"),
    new FFXIVMapDesc(`ffxiv/sea_s1/twn/s1t1/level/s1t1`, `La Noscea - Limsa Lominsa Upper Decks`),
    new FFXIVMapDesc(`ffxiv/sea_s1/twn/s1t2/level/s1t2`, `La Noscea - Limsa Lominsa Lower Decks`),

    new FFXIVMapDesc(`ffxiv/ocn_o1/fld/o1fa/level/o1fa`, `La Noscea - The Whorleater`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s2p1/level/s2p1`, `La Noscea - Seal Rock`),
    new FFXIVMapDesc(`ffxiv/sea_s1/bah/s1b1/level/s1b1`, `La Noscea - Upper Aetheroacoustic Exploratory Site`),
    new FFXIVMapDesc(`ffxiv/sea_s1/bah/s1b2/level/s1b2`, `La Noscea - Lower Aetheroacoustic Exploratory Site`),
    new FFXIVMapDesc(`ffxiv/sea_s1/bah/s1b3/level/s1b3`, `La Noscea - The Ragnarok - Engine Room`),
    new FFXIVMapDesc(`ffxiv/sea_s1/bah/s1b4/level/s1b4`, `La Noscea - Ragnarok Drive Cylinder`),
    new FFXIVMapDesc(`ffxiv/sea_s1/bah/s1b5/level/s1b5`, `La Noscea - Ragnarok Central Core`),
    new FFXIVMapDesc(`ffxiv/sea_s1/bah/s1b7/level/s1b7`, `La Noscea - Ragnarok Main Bridge`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d1/level/s1d1`, `La Noscea - Sastasha`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d2/level/s1d2`, `La Noscea - Brayflox's Longstop`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d3/level/s1d3`, `La Noscea - The Wanderer's Palace`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d4/level/s1d4`, `La Noscea - Pharos Sirius - Flood Cellar`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d5/level/s1d5`, `La Noscea - Hullbreaker Isle`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d6/level/s1d6`, `La Noscea - Brayflox's Longstop (Hard)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d7/level/s1d7`, `La Noscea - Sastasha (Hard)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d8/level/s1d8`, `La Noscea - The Wanderer's Palace (Hard)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d9/level/s1d9`, `La Noscea - Pharos Sirius (Hard) - Fifth & Fourth Levels`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1da/level/s1da`, `La Noscea - Hullbreaker Isle (Hard)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/evt/s1e4/level/s1e4`, `La Noscea - Command Room`),
    new FFXIVMapDesc(`ffxiv/sea_s1/evt/s1e8/level/s1e8`, `La Noscea - The Falling City of Nym`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1f1/level/s1f1`, `La Noscea - Middle La Noscea`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1f2/level/s1f2`, `La Noscea - Lower La Noscea`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1f3/level/s1f3`, `La Noscea - Eastern La Noscea`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1f4/level/s1f4`, `La Noscea - Western La Noscea`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1f5/level/s1f5`, `La Noscea - Upper La Noscea`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1f6/level/s1f6`, `La Noscea - Outer La Noscea`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1fa/level/s1fa`, `La Noscea - The Navel`),
    new FFXIVMapDesc(`ffxiv/sea_s1/hou/s1h1/level/s1h1`, `La Noscea - Mist - Mist`),
    new FFXIVMapDesc(`ffxiv/sea_s1/ind/s1i1/level/s1i1`, `La Noscea - Private Cottage - Mist - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/sea_s1/ind/s1i2/level/s1i2`, `La Noscea - Private House - Mist - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/sea_s1/ind/s1i3/level/s1i3`, `La Noscea - Private Mansion - Mist - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/sea_s1/ind/s1i4/level/s1i4`, `La Noscea - Private Chambers - Mist`),
    new FFXIVMapDesc(`ffxiv/sea_s1/ind/s1i5/level/s1i5`, `La Noscea - Company Workshop - Mist`),
    new FFXIVMapDesc(`ffxiv/sea_s1/ind/s1i6/level/s1i6`, `La Noscea - Topmast Apartment Lobby`),
    new FFXIVMapDesc(`ffxiv/sea_s1/pvp/s1p1/level/s1p1`, `La Noscea - Wolves' Den Pier`),
    new FFXIVMapDesc(`ffxiv/sea_s1/pvp/s1p6/level/s1p6`, `La Noscea - The Fold`),
    new FFXIVMapDesc(`ffxiv/sea_s1/twn/s1t1/level/s1t1`, `La Noscea - Limsa Lominsa Upper Decks`),
    new FFXIVMapDesc(`ffxiv/sea_s1/twn/s1t2/level/s1t2`, `La Noscea - Limsa Lominsa Lower Decks`),
    new FFXIVMapDesc(`ffxiv/sea_s1/twn/s1tg/level/s1tg`, `La Noscea - Maelstrom Barracks`),
    new FFXIVMapDesc(`ffxiv/sea_s1/twn/s1ti/level/s1ti`, `La Noscea - Mizzenmast Inn`),
    new FFXIVMapDesc(`ex2/03_ocn_o3/dun/o3d1/level/o3d1`, `La Noscea - The Sirensong Sea`),
    new FFXIVMapDesc(`ex2/03_ocn_o3/evt/o3e1/level/o3e1`, `La Noscea - The Misery`),
    "The Black Shroud",
    new FFXIVMapDesc(`ffxiv/fst_f1/bah/f1b1/level/f1b1`, `The Black Shroud - Dalamud's Shadow`),
    new FFXIVMapDesc(`ffxiv/fst_f1/bah/f1b2/level/f1b2`, `The Black Shroud - The Outer Coil - Incubation Bay`),
    new FFXIVMapDesc(`ffxiv/fst_f1/bah/f1b3/level/f1b3`, `The Black Shroud - Central Decks - Lower Decks`),
    new FFXIVMapDesc(`ffxiv/fst_f1/bah/f1b4/level/f1b4`, `The Black Shroud - The Holocharts`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d1/level/f1d1`, `The Black Shroud - The Tam-Tara Deepcroft`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d2/level/f1d2`, `The Black Shroud - Haukke Manor - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d3/level/f1d3`, `The Black Shroud - Amdapor Keep - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d4/level/f1d4`, `The Black Shroud - Haukke Manor (Hard) - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d5/level/f1d5`, `The Black Shroud - The Lost City of Amdapor - Central Amdapor`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d6/level/f1d6`, `The Black Shroud - The Tam-Tara Deepcroft (Hard)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d7/level/f1d7`, `The Black Shroud - Amdapor Keep (Hard) - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d8/level/f1d8`, `The Black Shroud - The Lost City of Amdapor (Hard) - Central Amdapor`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d9/level/f1d9`, `The Black Shroud - Haunted Manor - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1da/level/f1da`, `The Black Shroud - Baelsar's Wall - Lower Reaches`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1db/level/f1db`, `The Black Shroud - The Phantoms' Feast - Lower Sepulchres`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1dc/level/f1dc`, `The Black Shroud - Manor Basement`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1dd/level/f1dd`, `The Black Shroud - The Pâtisserie`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1e4/level/f1e4`, `The Black Shroud - Seat of the First Bow`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1e5/level/f1e5`, `The Black Shroud - Lotus Stand`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1e7/level/f1e7`, `The Black Shroud - The Palace of the Dead`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1e9/level/f1e9`, `The Black Shroud - Valentione's Ceremony`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1ea/level/f1ea`, `The Black Shroud - Sneaky Hollow`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1eb/level/f1eb`, `The Black Shroud - Sylphstep`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1ec/level/f1ec`, `The Black Shroud - Starlight Stalls`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1ed/level/f1ed`, `The Black Shroud - Lilyswim`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1f1/level/f1f1`, `The Black Shroud - Central Shroud`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1f2/level/f1f2`, `The Black Shroud - East Shroud`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1f3/level/f1f3`, `The Black Shroud - South Shroud`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1f4/level/f1f4`, `The Black Shroud - North Shroud`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1fa/level/f1fa`, `The Black Shroud - Thornmarch`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1fb/level/f1fb`, `The Black Shroud - The Striking Tree`),
    new FFXIVMapDesc(`ffxiv/fst_f1/hou/f1h1/level/f1h1`, `The Black Shroud - The Lavender Beds - The Lavender Beds`),
    new FFXIVMapDesc(`ffxiv/fst_f1/ind/f1i1/level/f1i1`, `The Black Shroud - Private Cottage - The Lavender Beds - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/fst_f1/ind/f1i2/level/f1i2`, `The Black Shroud - Private House - The Lavender Beds - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/fst_f1/ind/f1i3/level/f1i3`, `The Black Shroud - Private Mansion - The Lavender Beds - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/fst_f1/ind/f1i4/level/f1i4`, `The Black Shroud - Private Chambers - The Lavender Beds`),
    new FFXIVMapDesc(`ffxiv/fst_f1/ind/f1i5/level/f1i5`, `The Black Shroud - Company Workshop - The Lavender Beds`),
    new FFXIVMapDesc(`ffxiv/fst_f1/ind/f1i6/level/f1i6`, `The Black Shroud - Lily Hills Apartment Lobby`),
    new FFXIVMapDesc(`ffxiv/fst_f1/rad/f1r1/level/f1r1`, `The Black Shroud - The Thousand Maws of Toto-Rak`),
    new FFXIVMapDesc(`ffxiv/fst_f1/twn/f1t1/level/f1t1`, `The Black Shroud - New Gridania`),
    new FFXIVMapDesc(`ffxiv/fst_f1/twn/f1t2/level/f1t2`, `The Black Shroud - Old Gridania`),
    new FFXIVMapDesc(`ffxiv/fst_f1/twn/f1tg/level/f1tg`, `The Black Shroud - Twin Adder Barracks`),
    new FFXIVMapDesc(`ffxiv/fst_f1/twn/f1ti/level/f1ti`, `The Black Shroud - The Roost`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1f3/level/s1f3`, `The Black Shroud - South Shroud - Dock Storehouse`),
    "Thanalan",
    new FFXIVMapDesc(`ffxiv/lak_l1/evt/l1e2/level/l1e2`, `Thanalan - The Eighteenth Floor`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/w1p1/level/w1p1`, `Thanalan - Hidden Gorge`),
    new FFXIVMapDesc(`ffxiv/wil_w1/bah/w1b1/level/w1b1`, `Thanalan - IC-06 Central Decks`),
    new FFXIVMapDesc(`ffxiv/wil_w1/bah/w1b2/level/w1b2`, `Thanalan - IC-06 Regeneration Grid`),
    new FFXIVMapDesc(`ffxiv/wil_w1/bah/w1b3/level/w1b3`, `Thanalan - IC-06 Main Bridge`),
    new FFXIVMapDesc(`ffxiv/wil_w1/bah/w1b4/level/w1b4`, `Thanalan - The Burning Heart`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d1/level/w1d1`, `Thanalan - Copperbell Mines - Ground Level`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d2/level/w1d2`, `Thanalan - Halatali`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d4/level/w1d4`, `Thanalan - Castrum Meridianum`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d5/level/w1d5`, `Thanalan - The Praetorium - Sky Level`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d6/level/w1d6`, `Thanalan - Copperbell Mines (Hard) - Ground Level`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d7/level/w1d7`, `Thanalan - Halatali (Hard)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d8/level/w1d8`, `Thanalan - The Sunken Temple of Qarn (Hard) - Inner Sanctum`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1e4/level/w1e4`, `Thanalan - Heart of the Sworn`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1e6/level/w1e6`, `Thanalan - The Waking Sands`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1eb/level/w1eb`, `Thanalan - The Gold Saucer - The Gold Saucer`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1ed/level/w1ed`, `Thanalan - The Gold Saucer - Chocobo Square`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1ee/level/w1ee`, `Thanalan - The Battlehall`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1ef/level/w1ef`, `Thanalan - Frondale's Home for Friendless Foundlings`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1eg/level/w1eg`, `Thanalan - The Fall of Belah'dia`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1ej/level/w1ej`, `Thanalan - Lemures Headquarters`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1el/level/w1el`, `Thanalan - Blunderville Square`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1em/level/w1em`, `Thanalan - Hall of the Unbound`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1f1/level/w1f1`, `Thanalan - Western Thanalan`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1f2/level/w1f2`, `Thanalan - Central Thanalan`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1f3/level/w1f3`, `Thanalan - Eastern Thanalan`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1f4/level/w1f4`, `Thanalan - Southern Thanalan`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1f5/level/w1f5`, `Thanalan - Northern Thanalan`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1fa/level/w1fa`, `Thanalan - Bowl of Embers`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1fb/level/w1fb`, `Thanalan - Porta Decumana`),
    new FFXIVMapDesc(`ffxiv/wil_w1/hou/w1h1/level/w1h1`, `Thanalan - The Goblet - The Goblet`),
    new FFXIVMapDesc(`ffxiv/wil_w1/ind/w1i1/level/w1i1`, `Thanalan - Private Cottage - The Goblet - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/wil_w1/ind/w1i2/level/w1i2`, `Thanalan - Private House - The Goblet - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/wil_w1/ind/w1i3/level/w1i3`, `Thanalan - Private Mansion - The Goblet - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/wil_w1/ind/w1i4/level/w1i4`, `Thanalan - Private Chambers - The Goblet`),
    new FFXIVMapDesc(`ffxiv/wil_w1/ind/w1i5/level/w1i5`, `Thanalan - Company Workshop - The Goblet`),
    new FFXIVMapDesc(`ffxiv/wil_w1/ind/w1i6/level/w1i6`, `Thanalan - Sultana's Breath Apartment Lobby`),
    new FFXIVMapDesc(`ffxiv/wil_w1/rad/w1r1/level/w1r1`, `Thanalan - Cutter's Cry - The Dry Sands`),
    new FFXIVMapDesc(`ffxiv/wil_w1/twn/w1t1/level/w1t1`, `Thanalan - Ul'dah - Steps of Nald`),
    new FFXIVMapDesc(`ffxiv/wil_w1/twn/w1t2/level/w1t2`, `Thanalan - Ul'dah - Steps of Thal - Merchant Strip`),
    new FFXIVMapDesc(`ffxiv/wil_w1/twn/w1tg/level/w1tg`, `Thanalan - Flame Barracks`),
    new FFXIVMapDesc(`ffxiv/wil_w1/twn/w1ti/level/w1ti`, `Thanalan - The Hourglass`),
    new FFXIVMapDesc(`ffxiv/wil_w1/twn/w1tz/level/w1tz`, `Thanalan - Blue Sky`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fg/level/n4fg`, `Thanalan - Castrum Marinum Drydocks`),
    new FFXIVMapDesc(`ex3/04_wil_w4/dun/w4d1/level/w4d1`, `Thanalan - Paglth'an - Zolm'ak`),
    new FFXIVMapDesc(`ex4/06_wil_w5/dun/w5d1/level/w5d1`, `Thanalan - The Sil'dihn Subterrane`),
    new FFXIVMapDesc(`ex4/06_wil_w5/dun/w5d2/level/w5d2`, `Thanalan - Another Sil'dihn Subterrane - The Jewel`),
    "Coerthas",
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/r2p1/level/r2p1`, `Coerthas - The Fields of Glory`),
    new FFXIVMapDesc(`ffxiv/roc_r1/dun/r1d1/level/r1d1`, `Coerthas - Stone Vigil`),
    new FFXIVMapDesc(`ffxiv/roc_r1/dun/r1d2/level/r1d2`, `Coerthas - The Stone Vigil (Hard)`),
    new FFXIVMapDesc(`ffxiv/roc_r1/dun/r1d3/level/r1d3`, `Coerthas - Snowcloak`),
    new FFXIVMapDesc(`ffxiv/roc_r1/evt/r1e2/level/r1e2`, `Coerthas - Intercessory`),
    new FFXIVMapDesc(`ffxiv/roc_r1/evt/r1e3/level/r1e3`, `Coerthas - Steps of Faith`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1f1/level/r1f1`, `Coerthas - Coerthas Central Highlands`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1fa/level/r1fa`, `Coerthas - The Howling Eye`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1fb/level/r1fb`, `Coerthas - Griffin Crossing`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1fc/level/r1fc`, `Coerthas - Akh Afah Amphitheatre`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1fd/level/r1fd`, `Coerthas - Steps of Faith`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1fe/level/r1fe`, `Coerthas - Steps of Faith`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1fz/level/r1fz`, `Coerthas - Medias Res`),
    new FFXIVMapDesc(`ffxiv/roc_r1/hou/r1h1/level/r1h1`, `Coerthas - Empyreum - Empyreum`),
    new FFXIVMapDesc(`ffxiv/roc_r1/hou/r1hx/level/r1hx`, `Coerthas - The Firmament`),
    new FFXIVMapDesc(`ffxiv/roc_r1/ind/r1i1/level/r1i1`, `Coerthas - Private Cottage - Empyreum - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/roc_r1/ind/r1i2/level/r1i2`, `Coerthas - Private House - Empyreum - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/roc_r1/ind/r1i3/level/r1i3`, `Coerthas - Private Mansion - Empyreum - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/roc_r1/ind/r1i4/level/r1i4`, `Coerthas - Private Chambers - Empyreum`),
    new FFXIVMapDesc(`ffxiv/roc_r1/ind/r1i5/level/r1i5`, `Coerthas - Company Workshop - Empyreum`),
    new FFXIVMapDesc(`ffxiv/roc_r1/ind/r1i6/level/r1i6`, `Coerthas - Ingleside Apartment Lobby`),
    new FFXIVMapDesc(`ffxiv/roc_r1/rad/r1r1/level/r1r1`, `Coerthas - Dzemael Darkhold - Outer Hold`),
    new FFXIVMapDesc(`ffxiv/roc_r1/rad/r1r2/level/r1r2`, `Coerthas - Aurum Vale`),
    new FFXIVMapDesc(`ex1/01_roc_r2/dun/r2d1/level/r2d1`, `Coerthas - Dusk Vigil`),
    new FFXIVMapDesc(`ex1/01_roc_r2/dun/r2d2/level/r2d2`, `Coerthas - The Vault - Chantry Nave`),
    new FFXIVMapDesc(`ex1/01_roc_r2/dun/r2d3/level/r2d3`, `Coerthas - Xelphatol`),
    new FFXIVMapDesc(`ex1/01_roc_r2/evt/r2e1/level/r2e1`, `Coerthas - Saint Endalim's Scholasticate`),
    new FFXIVMapDesc(`ex1/01_roc_r2/evt/r2e3/level/r2e3`, `Coerthas - Seat of the Lord Commander`),
    new FFXIVMapDesc(`ex1/01_roc_r2/evt/r2e4/level/r2e4`, `Coerthas - Fortemps Manor`),
    new FFXIVMapDesc(`ex1/01_roc_r2/evt/r2e5/level/r2e5`, `Coerthas - The Lightfeather Proving Grounds`),
    new FFXIVMapDesc(`ex1/01_roc_r2/evt/r2e6/level/r2e6`, `Coerthas - Ruling Chamber`),
    new FFXIVMapDesc(`ex1/01_roc_r2/evt/r2ea/level/r2ea`, `Coerthas - Strategy Room`),
    new FFXIVMapDesc(`ex1/01_roc_r2/fld/r2f1/level/r2f1`, `Coerthas - Coerthas Western Highlands`),
    new FFXIVMapDesc(`ex1/01_roc_r2/twn/r2t1/level/r2t1`, `Coerthas - Foundation`),
    new FFXIVMapDesc(`ex1/01_roc_r2/twn/r2t2/level/r2t2`, `Coerthas - The Pillars`),
    new FFXIVMapDesc(`ex1/01_roc_r2/twn/r2ti/level/r2ti`, `Coerthas - Cloud Nine`),
    "Mor Dhona",
    new FFXIVMapDesc(`ffxiv/lak_l1/dun/l1d1/level/l1d1`, `Mor Dhona - The Keeper of the Lake - Forecastle`),
    new FFXIVMapDesc(`ffxiv/lak_l1/evt/l1e1/level/l1e1`, `Mor Dhona - The Rising Stones`),
    new FFXIVMapDesc(`ffxiv/lak_l1/evt/l1e3/level/l1e3`, `Mor Dhona - Omega Control`),
    new FFXIVMapDesc(`ffxiv/lak_l1/evt/l1e5/level/l1e5`, `Mor Dhona - The Syrcus Trench`),
    new FFXIVMapDesc(`ffxiv/lak_l1/fld/l1f1/level/l1f1`, `Mor Dhona - Mor Dhona`),
    new FFXIVMapDesc(`ffxiv/lak_l1/pvp/l1p1/level/l1p1`, `Mor Dhona - Carteneau Flats: Borderland Ruins`),
    new FFXIVMapDesc(`ffxiv/lak_l1/rad/l1r1/level/l1r1`, `Mor Dhona - Labyrinth of the Ancients - Lower Labyrinth`),
    new FFXIVMapDesc(`ffxiv/lak_l1/rad/l1r2/level/l1r2`, `Mor Dhona - Syrcus Tower - First Lower Ring`),
    new FFXIVMapDesc(`ffxiv/lak_l1/rad/l1r3/level/l1r3`, `Mor Dhona - The World of Darkness`),
    new FFXIVMapDesc(`ffxiv/zon_z1/evt/z1e9/level/z1e9`, `Mor Dhona - The Chrysalis`),
    new FFXIVMapDesc(`ex1/05_zon_z2/rad/z2r2/level/z2r2`, `Mor Dhona - The Weeping City of Mhach - Yafaem Saltmoor`),
    new FFXIVMapDesc(`ex4/07_lak_l5/cnt/l5c0/level/l5c0`, `Mor Dhona - Eureka Orthos`),
    "Abalathia's Spine",
    new FFXIVMapDesc(`ex1/03_abr_a2/dun/a2d1/level/a2d1`, `Abalathia's Spine - Aetherochemical Research Facility - Automachina Research`),
    new FFXIVMapDesc(`ex1/03_abr_a2/dun/a2d2/level/a2d2`, `Abalathia's Spine - Neverreap`),
    new FFXIVMapDesc(`ex1/03_abr_a2/dun/a2d3/level/a2d3`, `Abalathia's Spine - The Fractal Continuum - Forward Complex`),
    new FFXIVMapDesc(`ex1/03_abr_a2/dun/a2d4/level/a2d4`, `Abalathia's Spine - The Fractal Continuum (Hard) - Central Complex`),
    new FFXIVMapDesc(`ex1/03_abr_a2/evt/a2e2/level/a2e2`, `Abalathia's Spine - Central Azys Lla`),
    new FFXIVMapDesc(`ex1/03_abr_a2/evt/a2e3/level/a2e3`, `Abalathia's Spine - The Parrock`),
    new FFXIVMapDesc(`ex1/03_abr_a2/evt/a2e4/level/a2e4`, `Abalathia's Spine - Leofard's Chambers`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2f1/level/a2f1`, `Abalathia's Spine - The Sea of Clouds`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2f2/level/a2f2`, `Abalathia's Spine - Azys Lla`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fa/level/a2fa`, `Abalathia's Spine - The Limitless Blue`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fb/level/a2fb`, `Abalathia's Spine - Singularity Reactor`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fc/level/a2fc`, `Abalathia's Spine - `),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fd/level/a2fd`, `Abalathia's Spine - Containment Bay S1T7`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fe/level/a2fe`, `Abalathia's Spine - Containment Bay P1T6`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fg/level/a2fg`, `Abalathia's Spine - Containment Bay Z1T9`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fh/level/a2fh`, `Abalathia's Spine - `),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fx/level/a2fx`, `Abalathia's Spine - The Diadem`),
    new FFXIVMapDesc(`ex1/05_zon_z2/rad/z2r1/level/z2r1`, `Abalathia's Spine - Void Ark - Upper Deck`),
    new FFXIVMapDesc(`ex1/05_zon_z2/rad/z2r3/level/z2r3`, `Abalathia's Spine - Dun Scaith - The Lady Radlia`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3ff/level/e3ff`, `Abalathia's Spine - Last Remnant`),
    "Dravania",
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/d2p1/level/d2p1`, `Dravania - Astragalos`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a1/level/d2a1`, `Dravania - The Fist of the Father`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a2/level/d2a2`, `Dravania - The Cuff of the Father - Upper Ring`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a3/level/d2a3`, `Dravania - The Arm of the Father`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a4/level/d2a4`, `Dravania - The Burden of the Father`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a5/level/d2a5`, `Dravania - The Fist of the Son`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a6/level/d2a6`, `Dravania - The Cuff of the Son - Forward Ring`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a7/level/d2a7`, `Dravania - The Arm of the Son`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a8/level/d2a8`, `Dravania - The Burden of the Son`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a9/level/d2a9`, `Dravania - Eyes of the Creator - The Tipped Ewer`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2aa/level/d2aa`, `Dravania - Breath of the Creator - Illuminus`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2ab/level/d2ab`, `Dravania - Heart of the Creator - The Atrium`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2ac/level/d2ac`, `Dravania - Soul of the Creator`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d1/level/d2d1`, `Dravania - Sohm Al Foothills - The South Face`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d2/level/d2d2`, `Dravania - The Aery`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d3/level/d2d3`, `Dravania - The Great Gubal Library`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d4/level/d2d4`, `Dravania - Saint Mocianne's Arboretum - First Floor`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d5/level/d2d5`, `Dravania - The Antitower - Pleroma`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d6/level/d2d6`, `Dravania - Sohr Khai - An Answer of Sorrow`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d7/level/d2d7`, `Dravania - The Great Gubal Library (Hard) - Middle Floors`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d8/level/d2d8`, `Dravania - Sohm Al (Hard) - Betrayal`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d9/level/d2d9`, `Dravania - Saint Mocianne's Arboretum (Hard) - First Floor`),
    new FFXIVMapDesc(`ex1/02_dra_d2/evt/d2e2/level/d2e2`, `Dravania - Sacrificial Chamber`),
    new FFXIVMapDesc(`ex1/02_dra_d2/evt/d2e3/level/d2e3`, `Dravania - Matoya's Cave`),
    new FFXIVMapDesc(`ex1/02_dra_d2/evt/d2e4/level/d2e4`, `Dravania - The Gordian Knot`),
    new FFXIVMapDesc(`ex1/02_dra_d2/evt/d2e7/level/d2e7`, `Dravania - Heart of the Creator`),
    new FFXIVMapDesc(`ex1/02_dra_d2/fld/d2f1/level/d2f1`, `Dravania - The Dravanian Forelands`),
    new FFXIVMapDesc(`ex1/02_dra_d2/fld/d2f2/level/d2f2`, `Dravania - The Dravanian Hinterlands`),
    new FFXIVMapDesc(`ex1/02_dra_d2/fld/d2f3/level/d2f3`, `Dravania - The Churning Mists`),
    new FFXIVMapDesc(`ex1/02_dra_d2/fld/d2fa/level/d2fa`, `Dravania - Thok ast Thok`),
    new FFXIVMapDesc(`ex1/02_dra_d2/twn/d2t1/level/d2t1`, `Dravania - Idyllshire`),
    new FFXIVMapDesc(`ex3/02_dra_d4/dun/d4d1/level/d4d1`, `Dravania - Matoya's Relict - The Sorcerer's Interstice`),
    "Gyr Abania",
    new FFXIVMapDesc(`ex2/01_gyr_g3/dun/g3d1/level/g3d1`, `Gyr Abania - Castrum Abania`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/dun/g3d2/level/g3d2`, `Gyr Abania - Ala Mhigo - Mercantile District`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/dun/g3d3/level/g3d3`, `Gyr Abania - The Temple of the Fist - Dilemma`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/dun/g3d4/level/g3d4`, `Gyr Abania - The Drowned City of Skalla - The Shallows`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/dun/g3d5/level/g3d5`, `Gyr Abania - The Ghimlyt Dark`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/evt/g3e1/level/g3e1`, `Gyr Abania - The First Altar of Djanan Qhat`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/evt/g3e3/level/g3e3`, `Gyr Abania - The Resonatorium`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/evt/g3e4/level/g3e4`, `Gyr Abania - The Royal Menagerie`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/evt/g3e6/level/g3e6`, `Gyr Abania - The Resonatorium`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/evt/g3e7/level/g3e7`, `Gyr Abania - Garlean Legion Tents`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/fld/g3f1/level/g3f1`, `Gyr Abania - The Fringes`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/fld/g3f2/level/g3f2`, `Gyr Abania - The Peaks`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/fld/g3f3/level/g3f3`, `Gyr Abania - The Lochs`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/fld/g3fa/level/g3fa`, `Gyr Abania - Emanation`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/fld/g3fb/level/g3fb`, `Gyr Abania - The Royal Airship Landing`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/fld/g3fc/level/g3fc`, `Gyr Abania - Transparency`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/twn/g3t1/level/g3t1`, `Gyr Abania - Rhalgr's Reach`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o1/level/z3o1`, `Gyr Abania - The Interdimensional Rift`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o2/level/z3o2`, `Gyr Abania - Deltascape V1.0`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o3/level/z3o3`, `Gyr Abania - Deltascape V2.0`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o4/level/z3o4`, `Gyr Abania - Deltascape V3.0`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o5/level/z3o5`, `Gyr Abania - Deltascape V4.0`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o6/level/z3o6`, `Gyr Abania - The Interdimensional Rift`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o7/level/z3o7`, `Gyr Abania - Sigmascape V1.0`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o8/level/z3o8`, `Gyr Abania - Sigmascape V2.0`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o9/level/z3o9`, `Gyr Abania - Sigmascape V3.0`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3oa/level/z3oa`, `Gyr Abania - Sigmascape V4.0`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3ob/level/z3ob`, `Gyr Abania - The Interdimensional Rift`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3oc/level/z3oc`, `Gyr Abania - Psiscape V1.0`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3od/level/z3od`, `Gyr Abania - Psiscape V2.0`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3oe/level/z3oe`, `Gyr Abania - The Interdimensional Rift`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3of/level/z3of`, `Gyr Abania - The Interdimensional Rift`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fe/level/n4fe`, `Gyr Abania - Cinder Drift`),
    "Othard",
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/e3p1/level/e3p1`, `Othard - Onsal Hakair`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d1/level/e3d1`, `Othard - Shisui of the Violet Tides`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d2/level/e3d2`, `Othard - Bardam's Mettle`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d3/level/e3d3`, `Othard - Doma Castle`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d5/level/e3d5`, `Othard - Hells' Lid`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d6/level/e3d6`, `Othard - The Swallow's Compass - The Swallow's Compass`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d7/level/e3d7`, `Othard - The Burn`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3e5/level/e3e5`, `Othard - The House of the Fierce`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3e7/level/e3e7`, `Othard - Kienkan`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3e8/level/e3e8`, `Othard - Reisen Temple`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3e9/level/e3e9`, `Othard - The Burn`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3ea/level/e3ea`, `Othard - The Doman Enclave`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3eb/level/e3eb`, `Othard - The Doman Enclave`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3ec/level/e3ec`, `Othard - The Doman Enclave`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3ed/level/e3ed`, `Othard - Heaven-on-High`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3ee/level/e3ee`, `Othard - Castrum Fluminis`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3f1/level/e3f1`, `Othard - The Ruby Sea`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3f2/level/e3f2`, `Othard - Yanxia`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3f3/level/e3f3`, `Othard - The Azim Steppe`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3fa/level/e3fa`, `Othard - The Blessed Treasury`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3fb/level/e3fb`, `Othard - The Jade Stoa`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3fc/level/e3fc`, `Othard - The Great Hunt`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3fd/level/e3fd`, `Othard - Castrum Fluminis`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3fe/level/e3fe`, `Othard - Hells' Kier`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3fg/level/e3fg`, `Othard - The Wreath of Snakes`),
    "Hingashi",
    new FFXIVMapDesc(`ffxiv/est_e1/hou/e1h1/level/e1h1`, `Hingashi - Shirogane - Shirogane`),
    new FFXIVMapDesc(`ffxiv/est_e1/ind/e1i1/level/e1i1`, `Hingashi - Private Cottage - Shirogane - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/est_e1/ind/e1i2/level/e1i2`, `Hingashi - Private House - Shirogane - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/est_e1/ind/e1i3/level/e1i3`, `Hingashi - Private Mansion - Shirogane - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/est_e1/ind/e1i4/level/e1i4`, `Hingashi - Company Workshop - Shirogane`),
    new FFXIVMapDesc(`ffxiv/est_e1/ind/e1i5/level/e1i5`, `Hingashi - Private Chambers - Shirogane`),
    new FFXIVMapDesc(`ffxiv/est_e1/ind/e1i6/level/e1i6`, `Hingashi - Kobai Goten Apartment Lobby`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d4/level/e3d4`, `Hingashi - Kugane Castle - Ni-no-Maru`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3e1/level/e3e1`, `Hingashi - Ruby Bazaar Offices`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3ff/level/e3ff`, `Hingashi - Kugane Ohashi`),
    new FFXIVMapDesc(`ex2/02_est_e3/twn/e3t1/level/e3t1`, `Hingashi - Kugane`),
    new FFXIVMapDesc(`ex2/02_est_e3/twn/e3ti/level/e3ti`, `Hingashi - Bokairo Inn`),
    new FFXIVMapDesc(`ex4/08_est_e5/dun/e5d1/level/e5d1`, `Hingashi - Mount Rokkon - Mountain Base`),
    new FFXIVMapDesc(`ex4/08_est_e5/dun/e5d2/level/e5d2`, `Hingashi - Another Mount Rokkon - Path of the First Virtue`),
    "???",
    new FFXIVMapDesc(`ffxiv/cos_c1/hou/c1w1/level/c1w1`, `??? - Sinus Ardorum`),
    new FFXIVMapDesc(`ffxiv/cos_c1/hou/c1w2/level/c1w2`, `??? - Phaenna`),
    new FFXIVMapDesc(`ffxiv/cos_c1/hou/c1w3/level/c1w3`, `??? - Oizys`),
    new FFXIVMapDesc(`ffxiv/fst_f1/bah/f1bz/level/f1bz`, `??? - The Binding Coil of Bahamut`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1fc/level/f1fc`, `??? - Chocobo Square`),
    new FFXIVMapDesc(`ffxiv/hou_xx/hou/h1m2/level/h1m2`, `??? - Unnamed Island`),
    new FFXIVMapDesc(`ffxiv/hou_xx/ind/h1i1/level/h1i1`, `??? - Norvrandt - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/hou_xx/ind/h1i2/level/h1i2`, `??? - Eorzea - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/hou_xx/ind/h1i3/level/h1i3`, `??? - Hydaelyn - Ground Floor`),
    new FFXIVMapDesc(`ffxiv/lak_l1/rad/l1rz/level/l1rz`, `??? - Sphere of Naught`),
    new FFXIVMapDesc(`ffxiv/ocn_o1/ang/o1a1/level/o1a1`, `??? - The Endeavor`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s5p1/level/s5p1`, `??? - The Palaistra`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s5p2/level/s5p2`, `??? - The Volcanic Heart`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s5p3/level/s5p3`, `??? - Cloud Nine`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s5p4/level/s5p4`, `??? - The Clockwork Castletown`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s5p5/level/s5p5`, `??? - The Red Sands`),
    new FFXIVMapDesc(`ffxiv/sea_s1/bah/s1b7/level/s1b7`, `??? - Eorzean Subterrane`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1fb/level/s1fb`, `??? - Chocobo Square`),
    new FFXIVMapDesc(`ffxiv/wil_w1/cnt/w1c1/level/w1c1`, `??? - The Aquapolis`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1ek/level/w1ek`, `??? - Blunderville - Gentlebean's Fever`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1fc/level/w1fc`, `??? - Chocobo Square`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1fd/level/w1fd`, `??? - The Memory of Embers`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1fz/level/w1fz`, `??? - Ultimacy`),
    new FFXIVMapDesc(`ffxiv/zon_z1/jai/z1j1/level/z1j1`, `??? - Mordion Gaol`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2az/level/d2az`, `??? - Liminal Space`),
    new FFXIVMapDesc(`ex2/03_ocn_o3/cnt/o3c1/level/o3c1`, `??? - The Lost Canals of Uznair`),
    new FFXIVMapDesc(`ex2/03_ocn_o3/cnt/o3c2/level/o3c2`, `??? - The Shifting Altars of Uznair`),
    new FFXIVMapDesc(`ex2/05_zon_z3/btl/z3b1/level/z3b1`, `??? - The Imperial Palace`),
    new FFXIVMapDesc(`ex2/05_zon_z3/evt/z3e2/level/z3e2`, `??? - The Prima Vista Tiring Room`),
    new FFXIVMapDesc(`ex2/05_zon_z3/evt/z3e3/level/z3e3`, `??? - The Prima Vista Bridge`),
    new FFXIVMapDesc(`ex2/05_zon_z3/fld/z3fa/level/z3fa`, `??? - Eureka Anemos`),
    new FFXIVMapDesc(`ex2/05_zon_z3/fld/z3fb/level/z3fb`, `??? - Eureka Pagos`),
    new FFXIVMapDesc(`ex2/05_zon_z3/fld/z3fc/level/z3fc`, `??? - Eureka Pyros`),
    new FFXIVMapDesc(`ex2/05_zon_z3/fld/z3fd/level/z3fd`, `??? - Eureka Hydatos`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3oz/level/z3oz`, `??? - The Interdimensional Rift`),
    new FFXIVMapDesc(`ex2/05_zon_z3/rad/z3r1/level/z3r1`, `??? - The Royal City of Rabanastre - Charred Ruins`),
    new FFXIVMapDesc(`ex2/05_zon_z3/rad/z3r2/level/z3r2`, `??? - The Ridorana Lighthouse - The Ridorana Cataract`),
    new FFXIVMapDesc(`ex2/05_zon_z3/rad/z3r3/level/z3r3`, `??? - The Orbonne Monastery - The Golmore Jungle`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/btl/n4b2/level/n4b2`, `??? - Cid's Memory`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/btl/n4b3/level/n4b3`, `??? - Trial's Threshold`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/btl/n4b4/level/n4b4`, `??? - Bozjan Southern Front`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/btl/n4b5/level/n4b5`, `??? - Delubrum Reginae - Outer Locus`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/btl/n4b6/level/n4b6`, `??? - Zadnor`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/cnt/n4c1/level/n4c1`, `??? - The Dungeons of Lyhe Ghiah`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/cnt/n4c2/level/n4c2`, `??? - The Shifting Oubliettes of Lyhe Ghiah`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d9/level/n4d9`, `??? - Dreamlike Palace`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/evt/n4ea/level/n4ea`, `??? - Gangos`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/evt/n4eb/level/n4eb`, `??? - Terncliff`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4ff/level/n4ff`, `??? - The Seat of Sacrifice`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fh/level/n4fh`, `??? - G-Savior Deck`),
    new FFXIVMapDesc(`ex4/05_zon_z5/dun/z5d1/level/z5d1`, `??? - The Fell Court of Troia - Carcere IV`),
    new FFXIVMapDesc(`ex4/05_zon_z5/dun/z5d2/level/z5d2`, `??? - The Lunar Subterrane - The Lunar Subterrane`),
    new FFXIVMapDesc(`ex4/05_zon_z5/evt/z5e1/level/z5e1`, `??? - The Omphalos`),
    new FFXIVMapDesc(`ex4/05_zon_z5/evt/z5e4/level/z5e4`, `??? - Zero's Domain`),
    new FFXIVMapDesc(`ex4/05_zon_z5/evt/z5e5/level/z5e5`, `??? - The Red Moon`),
    new FFXIVMapDesc(`ex4/05_zon_z5/fld/z5fa/level/z5fa`, `??? - Storm's Crown`),
    new FFXIVMapDesc(`ex4/05_zon_z5/fld/z5fb/level/z5fb`, `??? - The Voidcast Dais`),
    new FFXIVMapDesc(`ex4/05_zon_z5/fld/z5fc/level/z5fc`, `??? - The Abyssal Fracture`),
    new FFXIVMapDesc(`ex4/05_zon_z5/rad/z5r1/level/z5r1`, `??? - Aglaia - Heaven of Lightning`),
    new FFXIVMapDesc(`ex4/05_zon_z5/rad/z5r2/level/z5r2`, `??? - Euphrosyne - Heaven of Earth`),
    new FFXIVMapDesc(`ex4/05_zon_z5/rad/z5r3/level/z5r3`, `??? - Thaleia - Heaven of Water`),
    new FFXIVMapDesc(`ex4/09_ocn_o5/dun/o5d1/level/o5d1`, `??? - Aloalo Island - Island Foreshore`),
    new FFXIVMapDesc(`ex4/09_ocn_o5/dun/o5d2/level/o5d2`, `??? - Another Aloalo Island - Dilumu`),
    new FFXIVMapDesc(`ex5/03_ocn_o6/btl/o6b1/level/o6b1`, `??? - South Horn`),
    new FFXIVMapDesc(`ex5/03_ocn_o6/evt/o6e1/level/o6e1`, `??? - Phantom Village`),
    new FFXIVMapDesc(`ex5/03_ocn_o6/evt/o6e2/level/o6e2`, `??? - Main Deck`),
    new FFXIVMapDesc(`ex5/05_zon_z6/evt/z6e1/level/z6e1`, `??? - Lower Jeuno`),
    new FFXIVMapDesc(`ex5/05_zon_z6/rad/z6r1/level/z6r1`, `??? - Jeuno: The First Walk - Lower Jeuno`),
    new FFXIVMapDesc(`ex5/05_zon_z6/rad/z6r2/level/z6r2`, `??? - San d'Oria: The Second Walk - San d'Oria`),
    "Norvrandt",
    new FFXIVMapDesc(`ex3/01_nvt_n4/btl/n4b1/level/n4b1`, `Norvrandt - The Confessional of Toupasa the Elder`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d1/level/n4d1`, `Norvrandt - Holminster Switch`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d2/level/n4d2`, `Norvrandt - Dohn Mheg - Lran Mheg`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d3/level/n4d3`, `Norvrandt - The Qitana Ravel - The Qitana Ravel`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d4/level/n4d4`, `Norvrandt - Malikah's Well - The Jasper Walls`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d5/level/n4d5`, `Norvrandt - Mt. Gulg - The Rise Above`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d6/level/n4d6`, `Norvrandt - Amaurot - Fading Footsteps`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d7/level/n4d7`, `Norvrandt - The Twinning - The Shallow`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d8/level/n4d8`, `Norvrandt - Akadaemia Anyder - The Halls`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d9/level/n4d9`, `Norvrandt - The Grand Cosmos`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4da/level/n4da`, `Norvrandt - Anamnesis Anyder - The Setebos Trench`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4db/level/n4db`, `Norvrandt - The Heroes' Gauntlet - Amh Araeng`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/evt/n4e1/level/n4e1`, `Norvrandt - The Ocular`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/evt/n4e8/level/n4e8`, `Norvrandt - Excavation Tunnels`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/evt/n4e9/level/n4e9`, `Norvrandt - Lyhe Mheg`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4f1/level/n4f1`, `Norvrandt - Lakeland`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4f2/level/n4f2`, `Norvrandt - Kholusia`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4f3/level/n4f3`, `Norvrandt - Amh Araeng`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4f4/level/n4f4`, `Norvrandt - Il Mheg`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4f5/level/n4f5`, `Norvrandt - The Rak'tika Greatwood`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4f6/level/n4f6`, `Norvrandt - The Tempest`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fa/level/n4fa`, `Norvrandt - The Dancing Plague`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fb/level/n4fb`, `Norvrandt - The Crown of the Immaculate`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fc/level/n4fc`, `Norvrandt - The Dying Gasp`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fd/level/n4fd`, `Norvrandt - The Dying Gasp`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g1/level/n4g1`, `Norvrandt - The Core`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g2/level/n4g2`, `Norvrandt - The Halo`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g3/level/n4g3`, `Norvrandt - The Nereus Trench`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g4/level/n4g4`, `Norvrandt - Atlas Peak`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g5/level/n4g5`, `Norvrandt - The Gandof Thunder Plains`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g6/level/n4g6`, `Norvrandt - Ashfall`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g7/level/n4g7`, `Norvrandt - The Halo`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g8/level/n4g8`, `Norvrandt - Great Glacier`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g9/level/n4g9`, `Norvrandt - Sphere of Naught`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4ga/level/n4ga`, `Norvrandt - Laxan Loft`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4gb/level/n4gb`, `Norvrandt - Bygone Gaol`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4gc/level/n4gc`, `Norvrandt - The Garden of Nowhere`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4gw/level/n4gw`, `Norvrandt - A Future Rewritten`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4gy/level/n4gy`, `Norvrandt - The Core`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4gz/level/n4gz`, `Norvrandt - The Empty`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/rad/n4r1/level/n4r1`, `Norvrandt - The Copied Factory - Upper Stratum`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/rad/n4r2/level/n4r2`, `Norvrandt - The Puppets' Bunker - The Duergar Mountains`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/rad/n4r3/level/n4r3`, `Norvrandt - The Tower at Paradigm's Breach - Lower Section`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/twn/n4t1/level/n4t1`, `Norvrandt - The Crystarium`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/twn/n4t2/level/n4t2`, `Norvrandt - Eulmore - The Buttress`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/twn/n4ti/level/n4ti`, `Norvrandt - The Pendants Personal Suite`),
    new FFXIVMapDesc(`ex5/06_nvt_n6/cnt/n6c0/level/n6c0`, `Norvrandt - Pilgrim's Traverse`),
    "The Source",
    "The First",
    "The Northern Empty",
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r9/level/n5r9`, `The Northern Empty - The Aetherial Slough`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5ra/level/n5ra`, `The Northern Empty - The Dæmons' Nest`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5rb/level/n5rb`, `The Northern Empty - The Chamber of Fourteen`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5rc/level/n5rc`, `The Northern Empty - Ascension`),
    new FFXIVMapDesc(`ex4/03_kld_k5/dun/k5d1/level/k5d1`, `The Northern Empty - The Aitiascope - Aetherial Lens`),
    new FFXIVMapDesc(`ex4/03_kld_k5/dun/k5d2/level/k5d2`, `The Northern Empty - The Aetherfont - Ice Field`),
    new FFXIVMapDesc(`ex4/03_kld_k5/evt/k5e1/level/k5e1`, `The Northern Empty - Main Hall`),
    new FFXIVMapDesc(`ex4/03_kld_k5/evt/k5e4/level/k5e4`, `The Northern Empty - Restricted Archives`),
    new FFXIVMapDesc(`ex4/03_kld_k5/evt/k5e5/level/k5e5`, `The Northern Empty - The Aitiascope - Aetherial Lens`),
    new FFXIVMapDesc(`ex4/03_kld_k5/fld/k5f1/level/k5f1`, `The Northern Empty - Labyrinthos`),
    new FFXIVMapDesc(`ex4/03_kld_k5/fld/k5fa/level/k5fa`, `The Northern Empty - The Mothercrystal`),
    new FFXIVMapDesc(`ex4/03_kld_k5/twn/k5t1/level/k5t1`, `The Northern Empty - Old Sharlayan`),
    new FFXIVMapDesc(`ex4/03_kld_k5/twn/k5ti/level/k5ti`, `The Northern Empty - Andron`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/evt/y6e3/level/y6e3`, `The Northern Empty - Main Deck`),
    "Ilsabard",
    new FFXIVMapDesc(`ex4/02_mid_m5/btl/m5b1/level/m5b1`, `Ilsabard - Magna Glacies`),
    new FFXIVMapDesc(`ex4/02_mid_m5/dun/m5d1/level/m5d1`, `Ilsabard - The Tower of Zot - Tower Base`),
    new FFXIVMapDesc(`ex4/02_mid_m5/dun/m5d2/level/m5d2`, `Ilsabard - The Tower of Babil - Magitek Freight Depot E`),
    new FFXIVMapDesc(`ex4/02_mid_m5/dun/m5d3/level/m5d3`, `Ilsabard - Vanaspati - Vanaspati`),
    new FFXIVMapDesc(`ex4/02_mid_m5/dun/m5d4/level/m5d4`, `Ilsabard - Alzadaal's Legacy - The Bhaflau Remnants`),
    new FFXIVMapDesc(`ex4/02_mid_m5/dun/m5d5/level/m5d5`, `Ilsabard - Lapis Manalis - Pes Albus`),
    new FFXIVMapDesc(`ex4/02_mid_m5/evt/m5e3/level/m5e3`, `Ilsabard - The Nethergate`),
    new FFXIVMapDesc(`ex4/02_mid_m5/evt/m5e4/level/m5e4`, `Ilsabard - Meghaduta Guest Chambers`),
    new FFXIVMapDesc(`ex4/02_mid_m5/evt/m5e5/level/m5e5`, `Ilsabard - Estinien's Chambers`),
    new FFXIVMapDesc(`ex4/02_mid_m5/evt/m5e6/level/m5e6`, `Ilsabard - Khadga`),
    new FFXIVMapDesc(`ex4/02_mid_m5/evt/m5e7/level/m5e7`, `Ilsabard - Senatus`),
    new FFXIVMapDesc(`ex4/02_mid_m5/fld/m5f1/level/m5f1`, `Ilsabard - Thavnair`),
    new FFXIVMapDesc(`ex4/02_mid_m5/fld/m5f2/level/m5f2`, `Ilsabard - Garlemald`),
    new FFXIVMapDesc(`ex4/02_mid_m5/fld/m5fa/level/m5fa`, `Ilsabard - Mount Ordeals`),
    new FFXIVMapDesc(`ex4/02_mid_m5/fld/m5fb/level/m5fb`, `Ilsabard - The Gilded Araya`),
    new FFXIVMapDesc(`ex4/02_mid_m5/twn/m5t1/level/m5t1`, `Ilsabard - Radz-at-Han`),
    "The Sea of Stars",
    new FFXIVMapDesc(`ex4/04_uvs_u5/cnt/u5c1/level/u5c1`, `The Sea of Stars - The Excitatron 6000`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/dun/u5d1/level/u5d1`, `The Sea of Stars - The Dead Ends - Ostrakon Hexi`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/dun/u5d2/level/u5d2`, `The Sea of Stars - Smileton - The Outsides`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/dun/u5d3/level/u5d3`, `The Sea of Stars - The Stigma Dreamscape - The Alphatron Star`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/evt/u5e1/level/u5e1`, `The Sea of Stars - Beyond the Stars`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/evt/u5e3/level/u5e3`, `The Sea of Stars - Elysion`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/fld/u5f1/level/u5f1`, `The Sea of Stars - Mare Lamentorum`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/fld/u5f2/level/u5f2`, `The Sea of Stars - Ultima Thule`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/fld/u5fa/level/u5fa`, `The Sea of Stars - The Dark Inside`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/fld/u5fb/level/u5fb`, `The Sea of Stars - The Final Day`),
    "The World Unsundered",
    new FFXIVMapDesc(`ex4/01_nvt_n5/cnt/n5c1/level/n5c1`, `The World Unsundered - The Shifting Gymnasion Agonon`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/dun/n5d1/level/n5d1`, `The World Unsundered - Ktisis Hyperboreia - Terrestrial Artifice`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/evt/n5e1/level/n5e1`, `The World Unsundered - Propylaion`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/fld/n5f1/level/n5f1`, `The World Unsundered - Elpis`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r0/level/n5r0`, `The World Unsundered - The Gates of Pandæmonium`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r1/level/n5r1`, `The World Unsundered - The Gates of Pandæmonium`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r2/level/n5r2`, `The World Unsundered - The Stagnant Limbo`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r3/level/n5r3`, `The World Unsundered - The Fervid Limbo`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r4/level/n5r4`, `The World Unsundered - The Sanguine Limbo`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r5/level/n5r5`, `The World Unsundered - The Caustic Purgatory`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r6/level/n5r6`, `The World Unsundered - The Pestilent Purgatory`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r7/level/n5r7`, `The World Unsundered - The Hollow Purgatory`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r8/level/n5r8`, `The World Unsundered - Stygian Insenescence Cells`),
    "Yok Tural",
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s5p6/level/s5p6`, `Yok Tural - The Bayside Battleground`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/y6p1/level/y6p1`, `Yok Tural - Worqor Chirteh`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/cnt/y6c1/level/y6c1`, `Yok Tural - Cenote Ja Ja Gural`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/dun/y6d1/level/y6d1`, `Yok Tural - Ihuykatumu - Downriver Ihuykatumu`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/dun/y6d2/level/y6d2`, `Yok Tural - Worqor Zormor - Zirgor Zormor`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/dun/y6d3/level/y6d3`, `Yok Tural - The Skydeep Cenote - Gok Draak Cenotaph`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/evt/y6e1/level/y6e1`, `Yok Tural - Sunperch`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/evt/y6e2/level/y6e2`, `Yok Tural - Skydeep Cenote Inner Chamber`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/evt/y6e5/level/y6e5`, `Yok Tural - Zirgorteh the Open-armed`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/fld/y6f1/level/y6f1`, `Yok Tural - Urqopacha`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/fld/y6f2/level/y6f2`, `Yok Tural - Kozama'uka`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/fld/y6f3/level/y6f3`, `Yok Tural - Yak T'el`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/fld/y6fa/level/y6fa`, `Yok Tural - Worqor Lar Dor`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/twn/y6t1/level/y6t1`, `Yok Tural - Tuliyollal`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/twn/y6ti/level/y6ti`, `Yok Tural - The For'ard Cabins`),
    "Xak Tural",
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d1/level/x6d1`, `Xak Tural - Vanguard`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d2/level/x6d2`, `Xak Tural - Origenics - Hover Docks`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d4/level/x6d4`, `Xak Tural - Tender Valley - Tender Valley`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d6/level/x6d6`, `Xak Tural - Yuweyawata - Wawsatenyazeto`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d7/level/x6d7`, `Xak Tural - The Underkeep - Foundation Sector`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e1/level/x6e1`, `Xak Tural - Earthen Sky Hideout`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e2/level/x6e2`, `Xak Tural - The Backroom`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e4/level/x6e4`, `Xak Tural - Tritails Training`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e5/level/x6e5`, `Xak Tural - Greenroom`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e7/level/x6e7`, `Xak Tural - Zorgor the Boundless`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e8/level/x6e8`, `Xak Tural - Break Room`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e9/level/x6e9`, `Xak Tural - Throne Room`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6eb/level/x6eb`, `Xak Tural - Containment Complex 10-29`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6ef/level/x6ef`, `Xak Tural - Tritails Training`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6f1/level/x6f1`, `Xak Tural - Shaaloani`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6f2/level/x6f2`, `Xak Tural - Heritage Found`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6fa/level/x6fa`, `Xak Tural - Summit of Everkeep`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6fd/level/x6fd`, `Xak Tural - Recollection`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6ff/level/x6ff`, `Xak Tural - The Windward Wilds`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r1/level/x6r1`, `Xak Tural - Scratching Ring`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r2/level/x6r2`, `Xak Tural - Lovely Lovering`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r3/level/x6r3`, `Xak Tural - Blasting Ring`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r4/level/x6r4`, `Xak Tural - The Thundering`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r5/level/x6r5`, `Xak Tural - Groovy Ring`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r6/level/x6r6`, `Xak Tural - Rebel Ring`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r7/level/x6r7`, `Xak Tural - Demolition Site - Residential Radius 8-71`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r8/level/x6r8`, `Xak Tural - Hunter's Ring`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r9/level/x6r9`, `Xak Tural - Ring Noir`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6ra/level/x6ra`, `Xak Tural - The X-Ring`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6rb/level/x6rb`, `Xak Tural - The Crown`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6rc/level/x6rc`, `Xak Tural - Arcadia`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/twn/x6t1/level/x6t1`, `Xak Tural - Solution Nine`),
    "Unlost World",
    new FFXIVMapDesc(`ex5/01_xkt_x6/cnt/x6c1/level/x6c1`, `Unlost World - Vault Oneiron`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d3/level/x6d3`, `Unlost World - Alexandria - The Dream She Lived`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d5/level/x6d5`, `Unlost World - Strayborough - Dreamborough South`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d8/level/x6d8`, `Unlost World - The Meso Terminal - Lower Circuits`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d9/level/x6d9`, `Unlost World - Mistwake - Quan Caverns`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6ed/level/x6ed`, `Unlost World - Alexandria Crater`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6ee/level/x6ee`, `Unlost World - Bentini Depot`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6f3/level/x6f3`, `Unlost World - Living Memory`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6fb/level/x6fb`, `Unlost World - Interphos`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6fe/level/x6fe`, `Unlost World - The Ageless Necropolis`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6fg/level/x6fg`, `Unlost World - Hell on Rails`),

];

const id = `FinalFantasyXIV`;
const name = "Final Fantasy XIV";

export const sceneGroup: SceneGroup = {
    id, name, sceneDescs,
};