import { SceneContext, SceneDesc, SceneGroup } from "../SceneBase";
import { GfxDevice } from "../gfx/platform/GfxPlatform";
import { SceneGfx } from "../viewer";

import { rust } from '../rustlib.js';
import { FFXIVFilesystem } from "./files/Filesystem";
import { SceneLoader } from "./sceneloader";
import { SceneNode } from "./scenegraph";
import { FFXivSceneRenderer } from "./render/render";

abstract class FFXIVSceneGraphDesc implements SceneDesc {
    constructor(public id: string, public name: string = id) {
    }

    async createScene(device: GfxDevice, context: SceneContext): Promise<SceneGfx> {
        rust.init_panic_hook();

        const fs = new FFXIVFilesystem(context.dataFetcher);

        console.time("Load FS");
        const sceneGraph = await this.createSceneGraph(fs);
        console.timeEnd("Load FS");

        return new FFXivSceneRenderer(device, fs, sceneGraph);
    }

    abstract createSceneGraph(fs: FFXIVFilesystem): Promise<SceneNode>
}

class FFXIVMapDesc extends FFXIVSceneGraphDesc {

    constructor(public override id: string, public override name: string = id) {
        super(id, name);
    }

    async createSceneGraph(fs: FFXIVFilesystem): Promise<SceneNode> {
        return await new SceneLoader(fs).loadLevel(this.id);
    }
}

class FFXIVSgbDesc extends FFXIVSceneGraphDesc {

    constructor(public override id: string, public override name: string = id) {
        super(id, name);
    }

    async createSceneGraph(fs: FFXIVFilesystem): Promise<SceneNode> {
        return await new SceneLoader(fs).createNodeFromGb(this.id, await fs.loadSgb(this.id));
    }
}

const sceneDescs = [
    "Debug",
    new FFXIVSgbDesc(`bgcommon/world/aet/shared/for_bg/sgbg_w_aet_001_01a.sgb`, "Limsa Aetheryte"),
    new FFXIVMapDesc(`ffxiv/sea_s1/twn/s1t1/level/s1t1`, `La Noscea - Limsa Lominsa Upper Decks`),
    new FFXIVMapDesc(`ffxiv/sea_s1/twn/s1t2/level/s1t2`, `La Noscea - Limsa Lominsa Lower Decks`),

    "(no name)",
    new FFXIVMapDesc(`ffxiv/hou_xx/ind/h1i1/level/h1i1`, `(empty name)`),
    new FFXIVMapDesc(`ffxiv/hou_xx/ind/h1i2/level/h1i2`, `(empty name)`),
    new FFXIVMapDesc(`ffxiv/hou_xx/ind/h1i3/level/h1i3`, `(empty name)`),
    "La Noscea",
    new FFXIVMapDesc(`ffxiv/sea_s1/twn/s1t1/level/s1t1`, `Limsa Lominsa - Limsa Lominsa Upper Decks`),
    new FFXIVMapDesc(`ffxiv/sea_s1/twn/s1t2/level/s1t2`, `Limsa Lominsa - Limsa Lominsa Lower Decks`),
    new FFXIVMapDesc(`ffxiv/sea_s1/twn/s1ti/level/s1ti`, `Limsa Lominsa - Mizzenmast Inn`),
    new FFXIVMapDesc(`ffxiv/sea_s1/twn/s1tg/level/s1tg`, `Limsa Lominsa - Maelstrom Barracks`),
    new FFXIVMapDesc(`ffxiv/sea_s1/pvp/s1p1/level/s1p1`, `Wolves' Den Pier - Wolves' Den Pier`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s2p1/level/s2p1`, `Wolves' Den Pier - Seal Rock (Duty: Seal Rock (Seize))`),
    new FFXIVMapDesc(`ffxiv/sea_s1/pvp/s1p5/level/s1p5`, `Wolves' Den Pier - The Feasting Grounds`),
    new FFXIVMapDesc(`ffxiv/sea_s1/pvp/s1p2/level/s1p2`, `La Noscea - The Fold (Duty: Avoid Area of Effect Attacks)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/pvp/s1p6/level/s1p6`, `La Noscea - The Fold (Duty: React to Attack Markers)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/ind/s1i1/level/s1i1`, `La Noscea - Private Cottage - Mist`),
    new FFXIVMapDesc(`ffxiv/sea_s1/ind/s1i2/level/s1i2`, `La Noscea - Private House - Mist`),
    new FFXIVMapDesc(`ffxiv/sea_s1/ind/s1i3/level/s1i3`, `La Noscea - Private Mansion - Mist`),
    new FFXIVMapDesc(`ffxiv/sea_s1/ind/s1i4/level/s1i4`, `La Noscea - Private Chambers - Mist`),
    new FFXIVMapDesc(`ffxiv/sea_s1/ind/s1i5/level/s1i5`, `La Noscea - Company Workshop - Mist`),
    new FFXIVMapDesc(`ffxiv/sea_s1/ind/s1i6/level/s1i6`, `La Noscea - Topmast Apartment Lobby`),
    new FFXIVMapDesc(`ffxiv/sea_s1/hou/s1h1/level/s1h1`, `La Noscea - Mist`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1f1/level/s1f1`, `La Noscea - Middle La Noscea`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1f2/level/s1f2`, `La Noscea - Lower La Noscea`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1f3/level/s1f3`, `La Noscea - Eastern La Noscea`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1f4/level/s1f4`, `La Noscea - Western La Noscea`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1f5/level/s1f5`, `La Noscea - Upper La Noscea`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1f6/level/s1f6`, `La Noscea - Outer La Noscea`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1fa/level/s1fa`, `La Noscea - The Navel (Duty: the Navel (Hard))`),
    new FFXIVMapDesc(`ffxiv/ocn_o1/fld/o1fa/level/o1fa`, `La Noscea - The Whorleater (Duty: the Whorleater (Hard))`),
    new FFXIVMapDesc(`ffxiv/sea_s1/fld/s1fb/level/s1fb`, `The Gold Saucer - Chocobo Square (Duty: Chocobo Race: Costa del Sol)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/evt/s1e4/level/s1e4`, `Limsa Lominsa - Command Room`),
    new FFXIVMapDesc(`ffxiv/ocn_o1/evt/o1e2/level/o1e2`, `La Noscea - Rhotano Sea (Duty: )`),
    new FFXIVMapDesc(`ex2/03_ocn_o3/evt/o3e1/level/o3e1`, `La Noscea - The Misery`),
    new FFXIVMapDesc(`ffxiv/sea_s1/evt/s1e8/level/s1e8`, `The Gold Saucer - The Falling City of Nym (Duty: Leap of Faith)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d1/level/s1d1`, `La Noscea - Sastasha (Duty: To Calmer Seas)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d7/level/s1d7`, `La Noscea - Sastasha (Duty: Sastasha (Hard))`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d2/level/s1d2`, `La Noscea - Brayflox's Longstop (Duty: Brayflox's Longstop)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d6/level/s1d6`, `La Noscea - Brayflox's Longstop (Duty: Brayflox's Longstop (Hard))`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d3/level/s1d3`, `La Noscea - The Wanderer's Palace (Duty: the Wanderer's Palace)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d8/level/s1d8`, `La Noscea - The Wanderer's Palace (Duty: the Wanderer's Palace (Hard))`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d4/level/s1d4`, `La Noscea - Pharos Sirius (Duty: Pharos Sirius)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d9/level/s1d9`, `La Noscea - Pharos Sirius (Duty: Pharos Sirius (Hard))`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1d5/level/s1d5`, `La Noscea - Hullbreaker Isle (Duty: Hullbreaker Isle)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/dun/s1da/level/s1da`, `La Noscea - Hullbreaker Isle (Duty: Hullbreaker Isle (Hard))`),
    new FFXIVMapDesc(`ex2/03_ocn_o3/dun/o3d1/level/o3d1`, `La Noscea - The Sirensong Sea (Duty: the Sirensong Sea)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/bah/s1b1/level/s1b1`, `La Noscea - Upper Aetheroacoustic Exploratory Site (Duty: the Binding Coil of Bahamut - Turn 1)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/bah/s1b2/level/s1b2`, `La Noscea - Lower Aetheroacoustic Exploratory Site (Duty: the Binding Coil of Bahamut - Turn 2)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/bah/s1b3/level/s1b3`, `La Noscea - The Ragnarok (Duty: the Binding Coil of Bahamut - Turn 3)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/bah/s1b4/level/s1b4`, `La Noscea - Ragnarok Drive Cylinder (Duty: the Binding Coil of Bahamut - Turn 4)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/bah/s1b5/level/s1b5`, `La Noscea - Ragnarok Central Core (Duty: the Binding Coil of Bahamut - Turn 5)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/bah/s1b7/level/s1b7`, `La Noscea - Ragnarok Main Bridge`),
    "The Black Shroud",
    new FFXIVMapDesc(`ffxiv/fst_f1/twn/f1t1/level/f1t1`, `Gridania - New Gridania`),
    new FFXIVMapDesc(`ffxiv/fst_f1/twn/f1t2/level/f1t2`, `Gridania - Old Gridania`),
    new FFXIVMapDesc(`ffxiv/fst_f1/twn/f1ti/level/f1ti`, `Gridania - The Roost`),
    new FFXIVMapDesc(`ffxiv/fst_f1/twn/f1tg/level/f1tg`, `Gridania - Twin Adder Barracks`),
    new FFXIVMapDesc(`ffxiv/fst_f1/rad/f1r1/level/f1r1`, `The Black Shroud - The Thousand Maws of Toto-Rak (Duty: the Thousand Maws of TotoRak)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/ind/f1i1/level/f1i1`, `The Black Shroud - Private Cottage - The Lavender Beds`),
    new FFXIVMapDesc(`ffxiv/fst_f1/ind/f1i2/level/f1i2`, `The Black Shroud - Private House - The Lavender Beds`),
    new FFXIVMapDesc(`ffxiv/fst_f1/ind/f1i3/level/f1i3`, `The Black Shroud - Private Mansion - The Lavender Beds`),
    new FFXIVMapDesc(`ffxiv/fst_f1/ind/f1i4/level/f1i4`, `The Black Shroud - Private Chambers - The Lavender Beds`),
    new FFXIVMapDesc(`ffxiv/fst_f1/ind/f1i5/level/f1i5`, `The Black Shroud - Company Workshop - The Lavender Beds`),
    new FFXIVMapDesc(`ffxiv/fst_f1/ind/f1i6/level/f1i6`, `The Black Shroud - Lily Hills Apartment Lobby`),
    new FFXIVMapDesc(`ffxiv/fst_f1/hou/f1h1/level/f1h1`, `The Black Shroud - The Lavender Beds`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1f1/level/f1f1`, `The Black Shroud - Central Shroud`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1f2/level/f1f2`, `The Black Shroud - East Shroud`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1f3/level/f1f3`, `The Black Shroud - South Shroud`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1f4/level/f1f4`, `The Black Shroud - North Shroud`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1fa/level/f1fa`, `The Black Shroud - Thornmarch (Duty: Thornmarch (Extreme))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1fb/level/f1fb`, `The Black Shroud - The Striking Tree (Duty: the Striking Tree (Hard))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/fld/f1fc/level/f1fc`, `The Gold Saucer - Chocobo Square (Duty: Chocobo Race: Tranquil Paths)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1e4/level/f1e4`, `Gridania - Seat of the First Bow`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1e5/level/f1e5`, `Gridania - Lotus Stand`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1e6/level/f1e6`, `The Black Shroud - Sanctum of the Twelve`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1e9/level/f1e9`, `The Black Shroud - Sanctum of the Twelve (Duty: the Valentione's Ceremony)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1e7/level/f1e7`, `The Black Shroud - The Palace of the Dead`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1ea/level/f1ea`, `The Black Shroud - Sneaky Hollow`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1ec/level/f1ec`, `The Black Shroud - Starlight Stalls`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1ed/level/f1ed`, `The Black Shroud - Lilyswim`),
    new FFXIVMapDesc(`ffxiv/fst_f1/evt/f1eb/level/f1eb`, `The Gold Saucer - Sylphstep (Duty: Leap of Faith)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d1/level/f1d1`, `The Black Shroud - The Tam-Tara Deepcroft (Duty: the TamTara Deepcroft)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d6/level/f1d6`, `The Black Shroud - The Tam-Tara Deepcroft (Duty: the TamTara Deepcroft (Hard))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d2/level/f1d2`, `The Black Shroud - Haukke Manor (Duty: Haukke Manor)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d4/level/f1d4`, `The Black Shroud - Haukke Manor (Duty: Haukke Manor (Hard))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d5/level/f1d5`, `The Black Shroud - The Lost City of Amdapor (Duty: the Lost City of Amdapor)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d8/level/f1d8`, `The Black Shroud - The Lost City of Amdapor (Duty: the Lost City of Amdapor (Hard))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d3/level/f1d3`, `The Black Shroud - Amdapor Keep (Duty: Amdapor Keep)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d7/level/f1d7`, `The Black Shroud - Amdapor Keep (Duty: Amdapor Keep (Hard))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1d9/level/f1d9`, `The Black Shroud - Haunted Manor (Duty: the Haunted Manor)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1da/level/f1da`, `The Black Shroud - Baelsar's Wall (Duty: Baelsar's Wall)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1db/level/f1db`, `The Black Shroud - The Phantoms' Feast (Duty: The Phantoms' Feast)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1dc/level/f1dc`, `The Black Shroud - Manor Basement (Duty: Mind over Manor)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/dun/f1dd/level/f1dd`, `The Black Shroud - The Pâtisserie (Duty: the Pâtisserie)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/cnt/f1c1/level/f1c1`, `The Black Shroud - The Palace of the Dead (Duty: the Palace of the Dead (Floors 1-10))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/cnt/f1c2/level/f1c2`, `The Black Shroud - The Palace of the Dead (Duty: the Palace of the Dead (Floors 11-20))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/cnt/f1c3/level/f1c3`, `The Black Shroud - The Palace of the Dead (Duty: the Palace of the Dead (Floors 21-30))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/cnt/f1c4/level/f1c4`, `The Black Shroud - The Palace of the Dead (Duty: the Palace of the Dead (Floors 31-40))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/cnt/f1c5/level/f1c5`, `The Black Shroud - The Palace of the Dead (Duty: the Palace of the Dead (Floors 51-60))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/cnt/f1c6/level/f1c6`, `The Black Shroud - The Palace of the Dead (Duty: the Palace of the Dead (Floors 81-90))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/cnt/f1c7/level/f1c7`, `The Black Shroud - The Palace of the Dead (Duty: the Palace of the Dead (Floors 151-160))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/cnt/f1c8/level/f1c8`, `The Black Shroud - The Palace of the Dead (Duty: the Palace of the Dead (Floors 111-120))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/cnt/f1c9/level/f1c9`, `The Black Shroud - The Palace of the Dead (Duty: the Palace of the Dead (Floors 131-140))`),
    new FFXIVMapDesc(`ffxiv/fst_f1/bah/f1b1/level/f1b1`, `The Black Shroud - Dalamud's Shadow (Duty: the Second Coil of Bahamut - Turn 1)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/bah/f1b2/level/f1b2`, `The Black Shroud - The Outer Coil (Duty: the Second Coil of Bahamut - Turn 2)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/bah/f1b3/level/f1b3`, `The Black Shroud - Central Decks (Duty: the Second Coil of Bahamut - Turn 3)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/bah/f1b4/level/f1b4`, `The Black Shroud - The Holocharts (Duty: the Second Coil of Bahamut - Turn 4)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/bah/f1b5/level/f1b5`, `The Black Shroud - Main Bridge`),
    "Thanalan",
    new FFXIVMapDesc(`ffxiv/wil_w1/twn/w1t1/level/w1t1`, `Ul'dah - Ul'dah - Steps of Nald`),
    new FFXIVMapDesc(`ffxiv/wil_w1/twn/w1t2/level/w1t2`, `Ul'dah - Ul'dah - Steps of Thal`),
    new FFXIVMapDesc(`ffxiv/wil_w1/twn/w1ti/level/w1ti`, `Ul'dah - The Hourglass`),
    new FFXIVMapDesc(`ffxiv/wil_w1/twn/w1tg/level/w1tg`, `Ul'dah - Flame Barracks`),
    new FFXIVMapDesc(`ffxiv/wil_w1/twn/w1tz/level/w1tz`, `Ul'dah - Blue Sky (Duty: A Golden Opportunity)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/rad/w1r1/level/w1r1`, `Thanalan - Cutter's Cry (Duty: The Harvest Begins)`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/w1p1/level/w1p1`, `Wolves' Den Pier - Hidden Gorge (Duty: Hidden Gorge)`),
    new FFXIVMapDesc(`ffxiv/sea_s1/pvp/s1p3/level/s1p3`, `The Gold Saucer - Chocobo Square (Duty: LoVM: Master Tournament)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/ind/w1i1/level/w1i1`, `Thanalan - Private Cottage - The Goblet`),
    new FFXIVMapDesc(`ffxiv/wil_w1/ind/w1i2/level/w1i2`, `Thanalan - Private House - The Goblet`),
    new FFXIVMapDesc(`ffxiv/wil_w1/ind/w1i3/level/w1i3`, `Thanalan - Private Mansion - The Goblet`),
    new FFXIVMapDesc(`ffxiv/wil_w1/ind/w1i4/level/w1i4`, `Thanalan - Private Chambers - The Goblet`),
    new FFXIVMapDesc(`ffxiv/wil_w1/ind/w1i5/level/w1i5`, `Thanalan - Company Workshop - The Goblet`),
    new FFXIVMapDesc(`ffxiv/wil_w1/ind/w1i6/level/w1i6`, `Thanalan - Sultana's Breath Apartment Lobby`),
    new FFXIVMapDesc(`ffxiv/wil_w1/hou/w1h1/level/w1h1`, `Thanalan - The Goblet`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1f1/level/w1f1`, `Thanalan - Western Thanalan`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1f2/level/w1f2`, `Thanalan - Central Thanalan`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1f3/level/w1f3`, `Thanalan - Eastern Thanalan`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1f4/level/w1f4`, `Thanalan - Southern Thanalan`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1f5/level/w1f5`, `Thanalan - Northern Thanalan`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1fa/level/w1fa`, `Thanalan - Bowl of Embers (Duty: the Bowl of Embers (Hard))`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1fb/level/w1fb`, `Thanalan - Porta Decumana (Duty: the Minstrel's Ballad: Ultima's Bane)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fg/level/n4fg`, `Thanalan - Castrum Marinum Drydocks (Duty: Castrum Marinum)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1fc/level/w1fc`, `The Gold Saucer - Chocobo Square (Duty: Chocobo Race: Sagolii Road)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1e4/level/w1e4`, `Ul'dah - Heart of the Sworn`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1ef/level/w1ef`, `Ul'dah - Frondale's Home for Friendless Foundlings`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1e6/level/w1e6`, `Thanalan - The Waking Sands`),
    new FFXIVMapDesc(`ffxiv/lak_l1/evt/l1e2/level/l1e2`, `Thanalan - The Eighteenth Floor`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1ej/level/w1ej`, `Thanalan - Lemures Headquarters`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1em/level/w1em`, `Thanalan - Hall of the Unbound`),
    new FFXIVMapDesc(`ffxiv/sea_s1/evt/s1e9/level/s1e9`, `The Gold Saucer - The Gold Saucer (Duty: Air Force One)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1eb/level/w1eb`, `The Gold Saucer - The Gold Saucer`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1ei/level/w1ei`, `The Gold Saucer - The Gold Saucer (Duty: Air Force One)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1ed/level/w1ed`, `The Gold Saucer - Chocobo Square`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1ee/level/w1ee`, `The Gold Saucer - The Battlehall (Duty: The Triple Triad Battlehall)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1eg/level/w1eg`, `The Gold Saucer - The Fall of Belah'dia (Duty: Leap of Faith)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1eh/level/w1eh`, `The Gold Saucer - The Manderville Tables (Duty: Four-player Mahjong (Quick Match, Kuitan Disabled))`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1el/level/w1el`, `The Gold Saucer - Blunderville Square`),
    new FFXIVMapDesc(`ffxiv/wil_w1/evt/w1ek/level/w1ek`, `The Gold Saucer - Blunderville (Duty: Blunderville)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d1/level/w1d1`, `Thanalan - Copperbell Mines (Duty: Copperbell Mines)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d6/level/w1d6`, `Thanalan - Copperbell Mines (Duty: Copperbell Mines (Hard))`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d7/level/w1d7`, `Thanalan - Halatali (Duty: the Dragon's Neck)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d3/level/w1d3`, `Thanalan - The Sunken Temple of Qarn (Duty: the Sunken Temple of Qarn)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d8/level/w1d8`, `Thanalan - The Sunken Temple of Qarn (Duty: the Sunken Temple of Qarn (Hard))`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d4/level/w1d4`, `Thanalan - Castrum Meridianum (Duty: Castrum Meridianum)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d5/level/w1d5`, `Thanalan - The Praetorium (Duty: the Praetorium)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/dun/w1d2/level/w1d2`, `Thanalan - Hall of the Bestiarii (Duty: A Relic Reborn: the Hydra)`),
    new FFXIVMapDesc(`ex3/04_wil_w4/dun/w4d1/level/w4d1`, `Thanalan - Paglth'an (Duty: Paglth'an)`),
    new FFXIVMapDesc(`ex4/06_wil_w5/dun/w5d1/level/w5d1`, `Thanalan - The Sil'dihn Subterrane (Duty: the Sil'dihn Subterrane)`),
    new FFXIVMapDesc(`ex4/06_wil_w5/dun/w5d2/level/w5d2`, `Thanalan - Another Sil'dihn Subterrane (Duty: Another Sil'dihn Subterrane)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/bah/w1b1/level/w1b1`, `Thanalan - IC-06 Central Decks (Duty: the Final Coil of Bahamut - Turn 1)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/bah/w1b2/level/w1b2`, `Thanalan - IC-06 Regeneration Grid (Duty: the Final Coil of Bahamut - Turn 2)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/bah/w1b3/level/w1b3`, `Thanalan - IC-06 Main Bridge (Duty: the Final Coil of Bahamut - Turn 3)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/bah/w1b4/level/w1b4`, `Thanalan - The Burning Heart (Duty: the Final Coil of Bahamut - Turn 4)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/bah/w1b5/level/w1b5`, `Thanalan - IC-04 Main Bridge`),
    "Coerthas",
    new FFXIVMapDesc(`ex1/01_roc_r2/twn/r2t1/level/r2t1`, `Ishgard - Foundation`),
    new FFXIVMapDesc(`ex1/01_roc_r2/twn/r2t2/level/r2t2`, `Ishgard - The Pillars`),
    new FFXIVMapDesc(`ex1/01_roc_r2/twn/r2ti/level/r2ti`, `Ishgard - Cloud Nine`),
    new FFXIVMapDesc(`ffxiv/roc_r1/rad/r1r1/level/r1r1`, `Coerthas - Dzemael Darkhold`),
    new FFXIVMapDesc(`ffxiv/roc_r1/rad/r1r2/level/r1r2`, `Coerthas - Aurum Vale`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/r2p1/level/r2p1`, `Wolves' Den Pier - The Fields of Glory (Duty: the Fields of Glory (Shatter))`),
    new FFXIVMapDesc(`ffxiv/roc_r1/ind/r1i1/level/r1i1`, `Ishgard - Private Cottage - Empyreum`),
    new FFXIVMapDesc(`ffxiv/roc_r1/ind/r1i2/level/r1i2`, `Ishgard - Private House - Empyreum`),
    new FFXIVMapDesc(`ffxiv/roc_r1/ind/r1i3/level/r1i3`, `Ishgard - Private Mansion - Empyreum`),
    new FFXIVMapDesc(`ffxiv/roc_r1/ind/r1i4/level/r1i4`, `Ishgard - Private Chambers - Empyreum`),
    new FFXIVMapDesc(`ffxiv/roc_r1/ind/r1i5/level/r1i5`, `Ishgard - Company Workshop - Empyreum`),
    new FFXIVMapDesc(`ffxiv/roc_r1/ind/r1i6/level/r1i6`, `Ishgard - Ingleside Apartment Lobby`),
    new FFXIVMapDesc(`ffxiv/roc_r1/hou/r1hx/level/r1hx`, `Ishgard - The Firmament`),
    new FFXIVMapDesc(`ffxiv/roc_r1/hou/r1h1/level/r1h1`, `Ishgard - Empyreum`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1f1/level/r1f1`, `Coerthas - Coerthas Central Highlands`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1fa/level/r1fa`, `Coerthas - The Howling Eye (Duty: the Howling Eye (Hard))`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1fb/level/r1fb`, `Coerthas - Griffin Crossing (Duty: Battle on the Big Bridge)`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1fd/level/r1fd`, `Coerthas - Steps of Faith (Duty: the Steps of Faith)`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1fe/level/r1fe`, `Coerthas - Steps of Faith (Duty: the Final Steps of Faith)`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1fc/level/r1fc`, `Coerthas - Akh Afah Amphitheatre (Duty: the Akh Afah Amphitheatre (Hard))`),
    new FFXIVMapDesc(`ex1/01_roc_r2/fld/r2f1/level/r2f1`, `Coerthas - Coerthas Western Highlands`),
    new FFXIVMapDesc(`ffxiv/roc_r1/fld/r1fz/level/r1fz`, `Coerthas - Medias Res (Duty: Dragonsong's Reprise (Ultimate))`),
    new FFXIVMapDesc(`ffxiv/roc_r1/evt/r1e3/level/r1e3`, `Coerthas - Steps of Faith`),
    new FFXIVMapDesc(`ffxiv/roc_r1/evt/r1e2/level/r1e2`, `Coerthas - Intercessory`),
    new FFXIVMapDesc(`ex1/01_roc_r2/evt/r2e5/level/r2e5`, `Ishgard - The Lightfeather Proving Grounds`),
    new FFXIVMapDesc(`ex1/01_roc_r2/evt/r2e4/level/r2e4`, `Ishgard - Fortemps Manor`),
    new FFXIVMapDesc(`ex1/01_roc_r2/evt/r2e3/level/r2e3`, `Ishgard - Seat of the Lord Commander`),
    new FFXIVMapDesc(`ex1/01_roc_r2/evt/r2e6/level/r2e6`, `Ishgard - Ruling Chamber`),
    new FFXIVMapDesc(`ex1/01_roc_r2/evt/r2e1/level/r2e1`, `Ishgard - Saint Endalim's Scholasticate`),
    new FFXIVMapDesc(`ex1/01_roc_r2/evt/r2ea/level/r2ea`, `Ishgard - Strategy Room`),
    new FFXIVMapDesc(`ffxiv/roc_r1/dun/r1d1/level/r1d1`, `Coerthas - Stone Vigil (Duty: the Stone Vigil)`),
    new FFXIVMapDesc(`ffxiv/roc_r1/dun/r1d2/level/r1d2`, `Coerthas - Stone Vigil (Duty: the Stone Vigil (Hard))`),
    new FFXIVMapDesc(`ffxiv/roc_r1/dun/r1d3/level/r1d3`, `Coerthas - Snowcloak (Duty: Snowcloak)`),
    new FFXIVMapDesc(`ex1/01_roc_r2/dun/r2d3/level/r2d3`, `Coerthas - Xelphatol (Duty: Xelphatol)`),
    new FFXIVMapDesc(`ex1/01_roc_r2/dun/r2d1/level/r2d1`, `Coerthas - Dusk Vigil (Duty: the Dusk Vigil)`),
    new FFXIVMapDesc(`ex1/01_roc_r2/dun/r2d2/level/r2d2`, `Ishgard - The Vault (Duty: )`),
    new FFXIVMapDesc(`ffxiv/wil_w1/cnt/w1c1/level/w1c1`, `Coerthas - The Aquapolis (Duty: the Aquapolis)`),
    "Mor Dhona",
    new FFXIVMapDesc(`ffxiv/lak_l1/rad/l1r1/level/l1r1`, `Mor Dhona - Labyrinth of the Ancients (Duty: the Labyrinth of the Ancients)`),
    new FFXIVMapDesc(`ffxiv/lak_l1/rad/l1r2/level/l1r2`, `Mor Dhona - Syrcus Tower (Duty: Syrcus Tower)`),
    new FFXIVMapDesc(`ffxiv/lak_l1/rad/l1r3/level/l1r3`, `Mor Dhona - The World of Darkness (Duty: the World of Darkness)`),
    new FFXIVMapDesc(`ffxiv/lak_l1/rad/l1rz/level/l1rz`, `Mor Dhona - Sphere of Naught (Duty: the Cloud of Darkness (Chaotic))`),
    new FFXIVMapDesc(`ex1/05_zon_z2/rad/z2r2/level/z2r2`, `Mor Dhona - The Weeping City of Mhach (Duty: the Weeping City of Mhach)`),
    new FFXIVMapDesc(`ffxiv/lak_l1/pvp/l1p1/level/l1p1`, `Wolves' Den Pier - Carteneau Flats: Borderland Ruins`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/l1p3/level/l1p3`, `Wolves' Den Pier - Carteneau Flats: Borderland Ruins (Duty: the Borderland Ruins (Secure))`),
    new FFXIVMapDesc(`ffxiv/lak_l1/fld/l1f1/level/l1f1`, `Mor Dhona - Mor Dhona`),
    new FFXIVMapDesc(`ffxiv/lak_l1/evt/l1e1/level/l1e1`, `Mor Dhona - The Rising Stones`),
    new FFXIVMapDesc(`ffxiv/zon_z1/evt/z1e9/level/z1e9`, `Mor Dhona - The Chrysalis (Duty: the Chrysalis)`),
    new FFXIVMapDesc(`ffxiv/lak_l1/evt/l1e3/level/l1e3`, `Mor Dhona - Omega Control`),
    new FFXIVMapDesc(`ffxiv/lak_l1/evt/l1e5/level/l1e5`, `Mor Dhona - The Syrcus Trench`),
    new FFXIVMapDesc(`ffxiv/lak_l1/dun/l1d1/level/l1d1`, `Mor Dhona - The Keeper of the Lake (Duty: the Keeper of the Lake)`),
    new FFXIVMapDesc(`ex4/07_lak_l5/cnt/l5c0/level/l5c0`, `Mor Dhona - Eureka Orthos`),
    new FFXIVMapDesc(`ex4/07_lak_l5/cnt/l5c1/level/l5c1`, `Mor Dhona - Eureka Orthos (Duty: Eureka Orthos (Floors 1-10))`),
    new FFXIVMapDesc(`ex4/07_lak_l5/cnt/l5c2/level/l5c2`, `Mor Dhona - Eureka Orthos (Duty: Eureka Orthos (Floors 11-20))`),
    new FFXIVMapDesc(`ex4/07_lak_l5/cnt/l5c3/level/l5c3`, `Mor Dhona - Eureka Orthos (Duty: Eureka Orthos (Floors 21-30))`),
    new FFXIVMapDesc(`ex4/07_lak_l5/cnt/l5c4/level/l5c4`, `Mor Dhona - Eureka Orthos (Duty: Eureka Orthos (Floors 41-50))`),
    new FFXIVMapDesc(`ex4/07_lak_l5/cnt/l5c5/level/l5c5`, `Mor Dhona - Eureka Orthos (Duty: Eureka Orthos (Floors 61-70))`),
    new FFXIVMapDesc(`ex4/07_lak_l5/cnt/l5c6/level/l5c6`, `Mor Dhona - Eureka Orthos (Duty: Eureka Orthos (Floors 81-90))`),
    "(no name)",
    new FFXIVMapDesc(`ffxiv/zon_z1/jai/z1j1/level/z1j1`, `Mordion Gaol`),
    new FFXIVMapDesc(`ffxiv/zon_z1/evt/z1e5/level/z1e5`, `Hall of Summoning`),
    "Abalathia's Spine",
    new FFXIVMapDesc(`ex1/05_zon_z2/rad/z2r3/level/z2r3`, `Abalathia's Spine - Dun Scaith (Duty: Dun Scaith)`),
    new FFXIVMapDesc(`ex1/05_zon_z2/rad/z2r1/level/z2r1`, `Abalathia's Spine - Void Ark (Duty: the Void Ark)`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fc/level/a2fc`, `Abalathia's Spine - The Diadem (Duty: the Diadem (Easy))`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fh/level/a2fh`, `Abalathia's Spine - The Diadem (Duty: the Diadem - Trials of the Matron)`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fx/level/a2fx`, `Abalathia's Spine - The Diadem (Duty: the Diadem)`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2f1/level/a2f1`, `Abalathia's Spine - The Sea of Clouds`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2f2/level/a2f2`, `Abalathia's Spine - Azys Lla`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fa/level/a2fa`, `Abalathia's Spine - The Limitless Blue (Duty: the Limitless Blue (Hard))`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fb/level/a2fb`, `Abalathia's Spine - Singularity Reactor (Duty: the Singularity Reactor)`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fd/level/a2fd`, `Abalathia's Spine - Containment Bay S1T7 (Duty: Containment Bay S1T7)`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fe/level/a2fe`, `Abalathia's Spine - Containment Bay P1T6 (Duty: Containment Bay P1T6)`),
    new FFXIVMapDesc(`ex1/03_abr_a2/fld/a2fg/level/a2fg`, `Abalathia's Spine - Containment Bay Z1T9 (Duty: Containment Bay Z1T9)`),
    new FFXIVMapDesc(`ex1/03_abr_a2/evt/a2e3/level/a2e3`, `Abalathia's Spine - The Parrock`),
    new FFXIVMapDesc(`ex1/03_abr_a2/evt/a2e4/level/a2e4`, `Abalathia's Spine - Leofard's Chambers`),
    new FFXIVMapDesc(`ex1/03_abr_a2/evt/a2e2/level/a2e2`, `Abalathia's Spine - Central Azys Lla`),
    new FFXIVMapDesc(`ex1/03_abr_a2/dun/a2d2/level/a2d2`, `Abalathia's Spine - Neverreap (Duty: Neverreap)`),
    new FFXIVMapDesc(`ex1/03_abr_a2/dun/a2d1/level/a2d1`, `Abalathia's Spine - Aetherochemical Research Facility (Duty: a Bloody Reunion)`),
    new FFXIVMapDesc(`ex1/03_abr_a2/dun/a2d3/level/a2d3`, `Abalathia's Spine - The Fractal Continuum (Duty: the Fractal Continuum)`),
    new FFXIVMapDesc(`ex1/03_abr_a2/dun/a2d4/level/a2d4`, `Abalathia's Spine - The Fractal Continuum (Duty: the Fractal Continuum (Hard))`),
    "Dravania",
    new FFXIVMapDesc(`ex1/02_dra_d2/twn/d2t1/level/d2t1`, `Idyllshire - Idyllshire`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/d2p1/level/d2p1`, `Wolves' Den Pier - Astragalos (Duty: Astragalos)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/fld/d2f1/level/d2f1`, `Dravania - The Dravanian Forelands`),
    new FFXIVMapDesc(`ex1/02_dra_d2/fld/d2f2/level/d2f2`, `Dravania - The Dravanian Hinterlands`),
    new FFXIVMapDesc(`ex1/02_dra_d2/fld/d2f3/level/d2f3`, `Dravania - The Churning Mists`),
    new FFXIVMapDesc(`ex1/02_dra_d2/fld/d2fa/level/d2fa`, `Dravania - Thok ast Thok (Duty: Thok ast Thok (Hard))`),
    new FFXIVMapDesc(`ex1/02_dra_d2/evt/d2e7/level/d2e7`, `Dravania - Heart of the Creator`),
    new FFXIVMapDesc(`ex1/02_dra_d2/evt/d2e3/level/d2e3`, `Dravania - Matoya's Cave`),
    new FFXIVMapDesc(`ex1/02_dra_d2/evt/d2e4/level/d2e4`, `Dravania - Alexander`),
    new FFXIVMapDesc(`ex1/02_dra_d2/evt/d2e5/level/d2e5`, `Dravania - Alexander`),
    new FFXIVMapDesc(`ex1/02_dra_d2/evt/d2e2/level/d2e2`, `Dravania - Sacrificial Chamber`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d1/level/d2d1`, `Dravania - Sohm Al (Duty: )`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d8/level/d2d8`, `Dravania - Sohm Al (Duty: Sohm Al (Hard))`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d4/level/d2d4`, `Dravania - Saint Mocianne's Arboretum (Duty: Saint Mocianne's Arboretum)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d9/level/d2d9`, `Dravania - Saint Mocianne's Arboretum (Duty: Saint Mocianne's Arboretum (Hard))`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d3/level/d2d3`, `Dravania - The Great Gubal Library (Duty: )`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d7/level/d2d7`, `Dravania - The Great Gubal Library (Duty: the Great Gubal Library (Hard))`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d2/level/d2d2`, `Dravania - The Aery (Duty: the Aery)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d5/level/d2d5`, `Dravania - The Antitower (Duty: the Antitower)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/dun/d2d6/level/d2d6`, `Dravania - Sohr Khai (Duty: Sohr Khai)`),
    new FFXIVMapDesc(`ex3/02_dra_d4/dun/d4d1/level/d4d1`, `Dravania - Matoya's Relict (Duty: Matoya's Relict)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a1/level/d2a1`, `Dravania - The Fist of the Father (Duty: Alexander - The Fist of the Father)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a2/level/d2a2`, `Dravania - The Cuff of the Father (Duty: Alexander - The Cuff of the Father)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a3/level/d2a3`, `Dravania - The Arm of the Father (Duty: Alexander - The Arm of the Father)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a4/level/d2a4`, `Dravania - The Burden of the Father (Duty: Alexander - The Burden of the Father)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a5/level/d2a5`, `Dravania - The Fist of the Son (Duty: Alexander - The Fist of the Son)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a6/level/d2a6`, `Dravania - The Cuff of the Son (Duty: Alexander - The Cuff of the Son)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a7/level/d2a7`, `Dravania - The Arm of the Son (Duty: Alexander - The Arm of the Son)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a8/level/d2a8`, `Dravania - The Burden of the Son (Duty: Alexander - The Burden of the Son)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2a9/level/d2a9`, `Dravania - Eyes of the Creator (Duty: Alexander - The Eyes of the Creator)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2aa/level/d2aa`, `Dravania - Breath of the Creator (Duty: Alexander - The Breath of the Creator)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2ab/level/d2ab`, `Dravania - Heart of the Creator (Duty: Alexander - The Heart of the Creator)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2ac/level/d2ac`, `Dravania - Soul of the Creator (Duty: Alexander - The Soul of the Creator)`),
    new FFXIVMapDesc(`ex1/02_dra_d2/alx/d2az/level/d2az`, `Dravania - Liminal Space (Duty: the Epic of Alexander (Ultimate))`),
    "Gyr Abania",
    new FFXIVMapDesc(`ex2/01_gyr_g3/twn/g3t1/level/g3t1`, `Rhalgr's Reach - Rhalgr's Reach`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o1/level/z3o1`, `Gyr Abania - The Interdimensional Rift (Duty: Interdimensional Rift)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o6/level/z3o6`, `Gyr Abania - The Interdimensional Rift (Duty: )`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3ob/level/z3ob`, `Gyr Abania - The Interdimensional Rift`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o2/level/z3o2`, `Gyr Abania - Deltascape V1.0 (Duty: Deltascape V1.0)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o3/level/z3o3`, `Gyr Abania - Deltascape V2.0 (Duty: Deltascape V2.0)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o4/level/z3o4`, `Gyr Abania - Deltascape V3.0 (Duty: Deltascape V3.0)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o5/level/z3o5`, `Gyr Abania - Deltascape V4.0 (Duty: Deltascape V4.0)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o7/level/z3o7`, `Gyr Abania - Sigmascape V1.0 (Duty: Sigmascape V1.0)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o8/level/z3o8`, `Gyr Abania - Sigmascape V2.0 (Duty: Sigmascape V2.0)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3o9/level/z3o9`, `Gyr Abania - Sigmascape V3.0 (Duty: Sigmascape V3.0)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3oa/level/z3oa`, `Gyr Abania - Sigmascape V4.0 (Duty: Sigmascape V4.0)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3oc/level/z3oc`, `Gyr Abania - Psiscape V1.0 (Duty: Alphascape V1.0)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3oe/level/z3oe`, `Gyr Abania - The Interdimensional Rift (Duty: Alphascape V3.0)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3od/level/z3od`, `Gyr Abania - Psiscape V2.0 (Duty: Alphascape V2.0)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3of/level/z3of`, `Gyr Abania - The Interdimensional Rift (Duty: Alphascape V4.0)`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/fld/g3fa/level/g3fa`, `Gyr Abania - Emanation (Duty: Emanation)`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/fld/g3f1/level/g3f1`, `Gyr Abania - The Fringes`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/fld/g3f2/level/g3f2`, `Gyr Abania - The Peaks`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/fld/g3f3/level/g3f3`, `Gyr Abania - The Lochs`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/fld/g3fb/level/g3fb`, `Gyr Abania - The Royal Airship Landing (Duty: the Royal Menagerie)`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/fld/g3fc/level/g3fc`, `Gyr Abania - Transparency (Duty: the Minstrel's Ballad: Shinryu's Domain)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fe/level/n4fe`, `Gyr Abania - Cinder Drift (Duty: Cinder Drift)`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/evt/g3e6/level/g3e6`, `Gyr Abania - The Resonatorium`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/evt/g3e1/level/g3e1`, `Gyr Abania - The First Altar of Djanan Qhat`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/evt/g3e3/level/g3e3`, `Gyr Abania - The Lochs (Duty: The Resonant)`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/evt/g3e4/level/g3e4`, `Gyr Abania - The Royal Menagerie`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/evt/g3e7/level/g3e7`, `Gyr Abania - Eorzean Alliance Headquarters`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/dun/g3d4/level/g3d4`, `Gyr Abania - The Drowned City of Skalla (Duty: the Drowned City of Skalla)`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/dun/g3d5/level/g3d5`, `Gyr Abania - The Ghimlyt Dark (Duty: a Requiem for Heroes)`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/dun/g3d1/level/g3d1`, `Gyr Abania - Castrum Abania (Duty: Castrum Abania)`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/dun/g3d2/level/g3d2`, `Gyr Abania - Ala Mhigo (Duty: Return of the Bull)`),
    new FFXIVMapDesc(`ex2/01_gyr_g3/dun/g3d3/level/g3d3`, `Gyr Abania - The Temple of the Fist (Duty: the Temple of the Fist)`),
    "Othard",
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/e3p1/level/e3p1`, `Wolves' Den Pier - Onsal Hakair (Duty: Onsal Hakair (Danshig Naadam))`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3fa/level/e3fa`, `Othard - The Blessed Treasury (Duty: the Pool of Tribute)`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3fb/level/e3fb`, `Othard - The Jade Stoa (Duty: the Jade Stoa)`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3f1/level/e3f1`, `Othard - The Ruby Sea`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3f2/level/e3f2`, `Othard - Yanxia`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3f3/level/e3f3`, `Othard - The Azim Steppe`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3fc/level/e3fc`, `Othard - The Great Hunt (Duty: the Great Hunt)`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3fd/level/e3fd`, `Othard - Castrum Fluminis (Duty: Castrum Fluminis)`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3fe/level/e3fe`, `Othard - Hells' Kier (Duty: Hells' Kier)`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3ff/level/e3ff`, `Othard - Kugane Ohashi (Duty: Special Event I)`),
    new FFXIVMapDesc(`ex2/02_est_e3/fld/e3fg/level/e3fg`, `Othard - The Wreath of Snakes (Duty: the Wreath of Snakes)`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3e8/level/e3e8`, `Othard - Reisen Temple`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3ed/level/e3ed`, `Othard - Heaven-on-High`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3ee/level/e3ee`, `Othard - Castrum Fluminis`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3e5/level/e3e5`, `Othard - The House of the Fierce`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3ea/level/e3ea`, `Othard - The Doman Enclave`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3eb/level/e3eb`, `Othard - The Doman Enclave`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3ec/level/e3ec`, `Othard - The Doman Enclave`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3e7/level/e3e7`, `Othard - Kienkan`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3e9/level/e3e9`, `Othard - The Burn (Duty: Emissary of the Dawn)`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d5/level/e3d5`, `Othard - Hells' Lid (Duty: Hells' Lid)`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d1/level/e3d1`, `Othard - Shisui of the Violet Tides (Duty: Shisui of the Violet Tides)`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d6/level/e3d6`, `Othard - The Swallow's Compass (Duty: the Swallow's Compass)`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d3/level/e3d3`, `Othard - Doma Castle (Duty: Doma Castle)`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d2/level/e3d2`, `Othard - Bardam's Mettle (Duty: Dragon Sound)`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d7/level/e3d7`, `Othard - The Burn (Duty: the Burn)`),
    new FFXIVMapDesc(`ex2/02_est_e3/cnt/e3c1/level/e3c1`, `Othard - Heaven-on-High (Duty: Heaven-on-High  (Floors 1-10))`),
    new FFXIVMapDesc(`ex2/02_est_e3/cnt/e3c2/level/e3c2`, `Othard - Heaven-on-High (Duty: Heaven-on-High  (Floors 11-20))`),
    new FFXIVMapDesc(`ex2/02_est_e3/cnt/e3c3/level/e3c3`, `Othard - Heaven-on-High (Duty: Heaven-on-High  (Floors 21-30))`),
    new FFXIVMapDesc(`ex2/02_est_e3/cnt/e3c4/level/e3c4`, `Othard - Heaven-on-High (Duty: Heaven-on-High  (Floors 41-50))`),
    new FFXIVMapDesc(`ex2/02_est_e3/cnt/e3c5/level/e3c5`, `Othard - Heaven-on-High (Duty: Heaven-on-High  (Floors 61-70))`),
    new FFXIVMapDesc(`ex2/02_est_e3/cnt/e3c6/level/e3c6`, `Othard - Heaven-on-High (Duty: Heaven-on-High  (Floors 81-90))`),
    "Hingashi",
    new FFXIVMapDesc(`ex2/02_est_e3/twn/e3t1/level/e3t1`, `Kugane - Kugane`),
    new FFXIVMapDesc(`ex2/02_est_e3/twn/e3ti/level/e3ti`, `Kugane - Bokairo Inn`),
    new FFXIVMapDesc(`ffxiv/est_e1/ind/e1i1/level/e1i1`, `Kugane - Private Cottage - Shirogane`),
    new FFXIVMapDesc(`ffxiv/est_e1/ind/e1i2/level/e1i2`, `Kugane - Private House - Shirogane`),
    new FFXIVMapDesc(`ffxiv/est_e1/ind/e1i3/level/e1i3`, `Kugane - Private Mansion - Shirogane`),
    new FFXIVMapDesc(`ffxiv/est_e1/ind/e1i4/level/e1i4`, `Kugane - Private Chambers - Shirogane`),
    new FFXIVMapDesc(`ffxiv/est_e1/ind/e1i5/level/e1i5`, `Kugane - Company Workshop - Shirogane`),
    new FFXIVMapDesc(`ffxiv/est_e1/ind/e1i6/level/e1i6`, `Kugane - Kobai Goten Apartment Lobby`),
    new FFXIVMapDesc(`ffxiv/est_e1/hou/e1h1/level/e1h1`, `Kugane - Shirogane`),
    new FFXIVMapDesc(`ex2/02_est_e3/evt/e3e1/level/e3e1`, `Kugane - Ruby Bazaar Offices`),
    new FFXIVMapDesc(`ex2/02_est_e3/dun/e3d4/level/e3d4`, `Kugane - Kugane Castle (Duty: Kugane Castle)`),
    new FFXIVMapDesc(`ex4/08_est_e5/dun/e5d1/level/e5d1`, `Kugane - Mount Rokkon (Duty: Mount Rokkon)`),
    new FFXIVMapDesc(`ex4/08_est_e5/dun/e5d2/level/e5d2`, `Kugane - Another Mount Rokkon (Duty: Another Mount Rokkon)`),
    "???",
    new FFXIVMapDesc(`ex2/05_zon_z3/rad/z3r1/level/z3r1`, `The Royal City of Rabanastre (Duty: the Royal City of Rabanastre)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/rad/z3r2/level/z3r2`, `The Ridorana Lighthouse (Duty: the Ridorana Lighthouse)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/rad/z3r3/level/z3r3`, `The Orbonne Monastery (Duty: the Orbonne Monastery)`),
    new FFXIVMapDesc(`ex4/05_zon_z5/rad/z5r1/level/z5r1`, `Aglaia (Duty: Aglaia)`),
    new FFXIVMapDesc(`ex4/05_zon_z5/rad/z5r2/level/z5r2`, `Euphrosyne (Duty: Euphrosyne)`),
    new FFXIVMapDesc(`ex4/05_zon_z5/rad/z5r3/level/z5r3`, `Thaleia (Duty: Thaleia)`),
    new FFXIVMapDesc(`ex5/05_zon_z6/rad/z6r1/level/z6r1`, `Jeuno: The First Walk (Duty: Jeuno: The First Walk)`),
    new FFXIVMapDesc(`ex5/05_zon_z6/rad/z6r2/level/z6r2`, `San d'Oria: The Second Walk (Duty: San d'Oria: The Second Walk)`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s5p1/level/s5p1`, `Wolves' Den Pier - The Palaistra (Duty: )`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s5p2/level/s5p2`, `Wolves' Den Pier - The Volcanic Heart (Duty: )`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s5p3/level/s5p3`, `Wolves' Den Pier - Cloud Nine (Duty: )`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s5p4/level/s5p4`, `Wolves' Den Pier - The Clockwork Castletown (Duty: the Clockwork Castletown)`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s5p5/level/s5p5`, `Wolves' Den Pier - The Red Sands (Duty: the Red Sands)`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/s5p6/level/s5p6`, `Wolves' Den Pier - The Bayside Battleground (Duty: the Bayside Battleground)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/ome/z3oz/level/z3oz`, `The Interdimensional Rift (Duty: the Omega Protocol (Ultimate))`),
    new FFXIVMapDesc(`ffxiv/hou_xx/hou/h1m2/level/h1m2`, `Unnamed Island`),
    new FFXIVMapDesc(`ex2/05_zon_z3/fld/z3fa/level/z3fa`, `Eureka Anemos (Duty: the Forbidden Land, Eureka Anemos)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1fz/level/w1fz`, `Ultimacy (Duty: the Weapon's Refrain (Ultimate))`),
    new FFXIVMapDesc(`ex2/05_zon_z3/fld/z3fb/level/z3fb`, `Eureka Pagos (Duty: the Forbidden Land, Eureka Pagos)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/fld/z3fc/level/z3fc`, `Eureka Pyros (Duty: the Forbidden Land, Eureka Pyros)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/fld/z3fd/level/z3fd`, `Eureka Hydatos (Duty: the Forbidden Land, Eureka Hydatos)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fh/level/n4fh`, `G-Savior Deck (Duty: the Cloud Deck)`),
    new FFXIVMapDesc(`ex4/05_zon_z5/fld/z5fa/level/z5fa`, `Storm's Crown (Duty: Storm's Crown)`),
    new FFXIVMapDesc(`ex4/05_zon_z5/fld/z5fb/level/z5fb`, `The Voidcast Dais (Duty: the Voidcast Dais)`),
    new FFXIVMapDesc(`ex4/05_zon_z5/fld/z5fc/level/z5fc`, `The Abyssal Fracture (Duty: the Abyssal Fracture)`),
    new FFXIVMapDesc(`ffxiv/wil_w1/fld/w1fd/level/w1fd`, `The Memory of Embers (Duty: Memory of Embers)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/evt/z3e2/level/z3e2`, `The Prima Vista Tiring Room`),
    new FFXIVMapDesc(`ex2/05_zon_z3/evt/z3e3/level/z3e3`, `The Prima Vista Bridge`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/evt/n4ea/level/n4ea`, `Gangos`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/evt/n4eb/level/n4eb`, `Terncliff`),
    new FFXIVMapDesc(`ex4/05_zon_z5/evt/z5e1/level/z5e1`, `The Omphalos`),
    new FFXIVMapDesc(`ex4/05_zon_z5/evt/z5e4/level/z5e4`, `Zero's Domain`),
    new FFXIVMapDesc(`ex4/05_zon_z5/evt/z5e5/level/z5e5`, `The Red Moon`),
    new FFXIVMapDesc(`ex5/03_ocn_o6/evt/o6e1/level/o6e1`, `Phantom Village`),
    new FFXIVMapDesc(`ex5/03_ocn_o6/evt/o6e2/level/o6e2`, `Main Deck`),
    new FFXIVMapDesc(`ex5/07_mid_m6/evt/m6e1/level/m6e1`, `The Maiden's Home`),
    new FFXIVMapDesc(`ex5/05_zon_z6/evt/z6e1/level/z6e1`, `Lower Jeuno`),
    new FFXIVMapDesc(`ex4/05_zon_z5/dun/z5d1/level/z5d1`, `The Fell Court of Troia (Duty: the Fell Court of Troia)`),
    new FFXIVMapDesc(`ex4/09_ocn_o5/dun/o5d1/level/o5d1`, `Aloalo Island (Duty: Aloalo Island)`),
    new FFXIVMapDesc(`ex4/09_ocn_o5/dun/o5d2/level/o5d2`, `Another Aloalo Island (Duty: Another Aloalo Island)`),
    new FFXIVMapDesc(`ex4/05_zon_z5/dun/z5d2/level/z5d2`, `The Lunar Subterrane (Duty: the Lunar Subterrane)`),
    new FFXIVMapDesc(`ex5/07_mid_m6/dun/m6d1/level/m6d1`, `The Merchant's Tale (Duty: The Merchant's Tale)`),
    new FFXIVMapDesc(`ex2/03_ocn_o3/cnt/o3c1/level/o3c1`, `The Lost Canals of Uznair (Duty: the Lost Canals of Uznair)`),
    new FFXIVMapDesc(`ex2/03_ocn_o3/cnt/o3c2/level/o3c2`, `The Shifting Altars of Uznair (Duty: the Shifting Altars of Uznair)`),
    new FFXIVMapDesc(`ex2/05_zon_z3/btl/z3b1/level/z3b1`, `The Imperial Palace (Duty: Vows of Virtue, Deeds of Cruelty)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/btl/n4b2/level/n4b2`, `Cid's Memory (Duty: the Bozja Incident)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/btl/n4b4/level/n4b4`, `Bozjan Southern Front (Duty: the Bozjan Southern Front)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/btl/n4b5/level/n4b5`, `Delubrum Reginae (Duty: Delubrum Reginae)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/btl/n4b6/level/n4b6`, `Zadnor (Duty: Zadnor)`),
    new FFXIVMapDesc(`ex5/03_ocn_o6/btl/o6b1/level/o6b1`, `South Horn (Duty: the Occult Crescent: South Horn)`),
    new FFXIVMapDesc(`ffxiv/fst_f1/bah/f1bz/level/f1bz`, `The Binding Coil of Bahamut (Duty: the Unending Coil of Bahamut (Ultimate))`),
    "Norvrandt",
    new FFXIVMapDesc(`ex3/01_nvt_n4/twn/n4t1/level/n4t1`, `The Crystarium - The Crystarium`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/twn/n4ti/level/n4ti`, `The Crystarium - The Pendants Personal Suite`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/twn/n4t2/level/n4t2`, `Eulmore - Eulmore`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/rad/n4r1/level/n4r1`, `Norvrandt - The Copied Factory (Duty: the Copied Factory)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/rad/n4r2/level/n4r2`, `Norvrandt - The Puppets' Bunker (Duty: the Puppets' Bunker)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/rad/n4r3/level/n4r3`, `Norvrandt - The Tower at Paradigm's Breach (Duty: the Tower at Paradigm's Breach)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g1/level/n4g1`, `Norvrandt - The Core (Duty: Eden's Gate: Resurrection)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4gy/level/n4gy`, `Norvrandt - The Core`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g2/level/n4g2`, `Norvrandt - The Halo (Duty: Eden's Gate: Descent)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g3/level/n4g3`, `Norvrandt - The Nereus Trench (Duty: Eden's Gate: Inundation)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g4/level/n4g4`, `Norvrandt - Atlas Peak (Duty: Eden's Gate: Sepulture)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4gz/level/n4gz`, `Norvrandt - The Empty`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g5/level/n4g5`, `Norvrandt - The Gandof Thunder Plains (Duty: Eden's Verse: Fulmination)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g6/level/n4g6`, `Norvrandt - Ashfall (Duty: Eden's Verse: Furor)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g7/level/n4g7`, `Norvrandt - The Halo (Duty: Eden's Verse: Iconoclasm)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g8/level/n4g8`, `Norvrandt - Great Glacier (Duty: Eden's Verse: Refulgence)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4gb/level/n4gb`, `Norvrandt - Bygone Gaol (Duty: Eden's Promise: Anamorphosis)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4g9/level/n4g9`, `Norvrandt - Sphere of Naught (Duty: Eden's Promise: Umbra)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4ga/level/n4ga`, `Norvrandt - Laxan Loft (Duty: Eden's Promise: Litany)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4gc/level/n4gc`, `Norvrandt - The Garden of Nowhere (Duty: Eden's Promise: Eternity)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/goe/n4gw/level/n4gw`, `Norvrandt - A Future Rewritten (Duty: Futures Rewritten (Ultimate))`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4f1/level/n4f1`, `Norvrandt - Lakeland`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4f2/level/n4f2`, `Norvrandt - Kholusia`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4f3/level/n4f3`, `Norvrandt - Amh Araeng`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4f4/level/n4f4`, `Norvrandt - Il Mheg`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4f5/level/n4f5`, `Norvrandt - The Rak'tika Greatwood`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4f6/level/n4f6`, `Norvrandt - The Tempest`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fa/level/n4fa`, `Norvrandt - The Dancing Plague (Duty: Special Event II)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fb/level/n4fb`, `Norvrandt - The Crown of the Immaculate (Duty: the Crown of the Immaculate)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fc/level/n4fc`, `Norvrandt - The Dying Gasp (Duty: the Dying Gasp)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4fd/level/n4fd`, `Norvrandt - The Dying Gasp (Duty: the Minstrel's Ballad: Hades's Elegy)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/fld/n4ff/level/n4ff`, `Norvrandt - The Seat of Sacrifice (Duty: the Seat of Sacrifice)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/evt/n4e1/level/n4e1`, `The Crystarium - The Ocular`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/evt/n4e8/level/n4e8`, `Norvrandt - Excavation Tunnels`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/evt/n4e9/level/n4e9`, `Norvrandt - Lyhe Mheg`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d2/level/n4d2`, `Norvrandt - Dohn Mheg (Duty: Dohn Mheg)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d7/level/n4d7`, `Norvrandt - The Twinning (Duty: the Twinning)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d6/level/n4d6`, `Norvrandt - Amaurot (Duty: Amaurot)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d5/level/n4d5`, `Norvrandt - Mt. Gulg (Duty: Mt. Gulg)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d8/level/n4d8`, `Norvrandt - Akadaemia Anyder (Duty: Akadaemia Anyder)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d3/level/n4d3`, `Norvrandt - The Qitana Ravel (Duty: the Qitana Ravel)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d1/level/n4d1`, `Norvrandt - Holminster Switch (Duty: Holminster Switch)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d4/level/n4d4`, `Norvrandt - Malikah's Well (Duty: Malikah's Well)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4d9/level/n4d9`, `Norvrandt - The Grand Cosmos (Duty: the Grand Cosmos)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4da/level/n4da`, `Norvrandt - Anamnesis Anyder (Duty: Anamnesis Anyder)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/dun/n4db/level/n4db`, `Norvrandt - The Heroes' Gauntlet (Duty: the Heroes' Gauntlet)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/cnt/n4c1/level/n4c1`, `Norvrandt - The Dungeons of Lyhe Ghiah (Duty: The Dungeons of Lyhe Ghiah)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/cnt/n4c2/level/n4c2`, `Norvrandt - The Shifting Oubliettes of Lyhe Ghiah (Duty: the Shifting Oubliettes of Lyhe Ghiah)`),
    new FFXIVMapDesc(`ex5/06_nvt_n6/cnt/n6c0/level/n6c0`, `Norvrandt - Pilgrim's Traverse`),
    new FFXIVMapDesc(`ex5/06_nvt_n6/cnt/n6c1/level/n6c1`, `Norvrandt - Pilgrim's Traverse (Duty: Pilgrim's Traverse (Stones 1-10))`),
    new FFXIVMapDesc(`ex5/06_nvt_n6/cnt/n6c2/level/n6c2`, `Norvrandt - Pilgrim's Traverse (Duty: Pilgrim's Traverse (Stones 11-20))`),
    new FFXIVMapDesc(`ex5/06_nvt_n6/cnt/n6c3/level/n6c3`, `Norvrandt - Pilgrim's Traverse (Duty: Pilgrim's Traverse (Stones 21-30))`),
    new FFXIVMapDesc(`ex5/06_nvt_n6/cnt/n6c4/level/n6c4`, `Norvrandt - Pilgrim's Traverse (Duty: Pilgrim's Traverse (Stones 41-50))`),
    new FFXIVMapDesc(`ex5/06_nvt_n6/cnt/n6c5/level/n6c5`, `Norvrandt - Pilgrim's Traverse (Duty: Pilgrim's Traverse (Stones 61-70))`),
    new FFXIVMapDesc(`ex5/06_nvt_n6/cnt/n6c6/level/n6c6`, `Norvrandt - Pilgrim's Traverse (Duty: Pilgrim's Traverse (Stones 81-90))`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/btl/n4b1/level/n4b1`, `Norvrandt - The Confessional of Toupasa the Elder (Duty: Legend of the Not-so-hidden Temple)`),
    new FFXIVMapDesc(`ex3/01_nvt_n4/btl/n4b3/level/n4b3`, `Norvrandt - Trial's Threshold (Duty: A Sleep Disturbed)`),
    "The High Seas",
    new FFXIVMapDesc(`ffxiv/ocn_o1/ang/o1a1/level/o1a1`, `The Endeavor (Duty: Ocean Fishing)`),
    new FFXIVMapDesc(`ffxiv/ocn_o1/ang/o1a2/level/o1a2`, `The Endeavor (Duty: Ocean Fishing)`),
    "The Northern Empty",
    new FFXIVMapDesc(`ex4/03_kld_k5/twn/k5t1/level/k5t1`, `Old Sharlayan - Old Sharlayan`),
    new FFXIVMapDesc(`ex4/03_kld_k5/twn/k5ti/level/k5ti`, `Old Sharlayan - Andron`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5rb/level/n5rb`, `Labyrinthos - The Chamber of Fourteen (Duty: Anabaseios: The Eleventh Circle)`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r9/level/n5r9`, `Labyrinthos - The Aetherial Slough (Duty: Anabaseios: The Ninth Circle)`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5ra/level/n5ra`, `Labyrinthos - The Dæmons' Nest (Duty: Anabaseios: The Tenth Circle)`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5rc/level/n5rc`, `Labyrinthos - Ascension (Duty: Anabaseios: The Twelfth Circle)`),
    new FFXIVMapDesc(`ex4/03_kld_k5/fld/k5fa/level/k5fa`, `Labyrinthos - The Mothercrystal (Duty: the Mothercrystal)`),
    new FFXIVMapDesc(`ex4/03_kld_k5/fld/k5f1/level/k5f1`, `Labyrinthos - Labyrinthos`),
    new FFXIVMapDesc(`ex4/03_kld_k5/evt/k5e2/level/k5e2`, `Labyrinthos`),
    new FFXIVMapDesc(`ex4/03_kld_k5/evt/k5e5/level/k5e5`, `Labyrinthos - The Aitiascope`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/evt/y6e3/level/y6e3`, `Labyrinthos - Main Deck`),
    new FFXIVMapDesc(`ex4/03_kld_k5/evt/k5e1/level/k5e1`, `Old Sharlayan - Main Hall`),
    new FFXIVMapDesc(`ex4/03_kld_k5/evt/k5e4/level/k5e4`, `Old Sharlayan - Restricted Archives`),
    new FFXIVMapDesc(`ex4/03_kld_k5/dun/k5d1/level/k5d1`, `Labyrinthos - The Aitiascope (Duty: the Aitiascope)`),
    new FFXIVMapDesc(`ex4/03_kld_k5/dun/k5d2/level/k5d2`, `Labyrinthos - The Aetherfont (Duty: the Aetherfont)`),
    "Ilsabard",
    new FFXIVMapDesc(`ex4/02_mid_m5/twn/m5t1/level/m5t1`, `Radz-at-Han - Radz-at-Han`),
    new FFXIVMapDesc(`ex4/02_mid_m5/fld/m5f1/level/m5f1`, `Thavnair - Thavnair`),
    new FFXIVMapDesc(`ex4/02_mid_m5/fld/m5fa/level/m5fa`, `Thavnair - Mount Ordeals (Duty: Mount Ordeals)`),
    new FFXIVMapDesc(`ex4/02_mid_m5/fld/m5fb/level/m5fb`, `Thavnair - The Gilded Araya (Duty: The Gilded Araya)`),
    new FFXIVMapDesc(`ex4/02_mid_m5/fld/m5f2/level/m5f2`, `Garlemald - Garlemald`),
    new FFXIVMapDesc(`ex4/02_mid_m5/evt/m5e3/level/m5e3`, `Thavnair - The Nethergate`),
    new FFXIVMapDesc(`ex4/02_mid_m5/evt/m5e6/level/m5e6`, `Thavnair - Khadga`),
    new FFXIVMapDesc(`ex4/02_mid_m5/evt/m5e1/level/m5e1`, `Radz-at-Han`),
    new FFXIVMapDesc(`ex4/02_mid_m5/evt/m5e4/level/m5e4`, `Radz-at-Han - Meghaduta Guest Chambers`),
    new FFXIVMapDesc(`ex4/02_mid_m5/evt/m5e5/level/m5e5`, `Radz-at-Han - Estinien's Chambers`),
    new FFXIVMapDesc(`ex4/02_mid_m5/evt/m5e7/level/m5e7`, `Garlemald - Senatus`),
    new FFXIVMapDesc(`ex4/02_mid_m5/dun/m5d1/level/m5d1`, `Thavnair - The Tower of Zot (Duty: the Tower of Zot)`),
    new FFXIVMapDesc(`ex4/02_mid_m5/dun/m5d3/level/m5d3`, `Thavnair - Vanaspati (Duty: Vanaspati)`),
    new FFXIVMapDesc(`ex4/02_mid_m5/dun/m5d2/level/m5d2`, `Thavnair - The Tower of Babil (Duty: the Tower of Babil)`),
    new FFXIVMapDesc(`ex4/02_mid_m5/dun/m5d4/level/m5d4`, `Thavnair - Alzadaal's Legacy (Duty: Alzadaal's Legacy)`),
    new FFXIVMapDesc(`ex4/02_mid_m5/dun/m5d5/level/m5d5`, `Thavnair - Lapis Manalis (Duty: Lapis Manalis)`),
    new FFXIVMapDesc(`ex4/02_mid_m5/btl/m5b1/level/m5b1`, `Thavnair - Magna Glacies (Duty: A Frosty Reception)`),
    "The Sea of Stars",
    new FFXIVMapDesc(`ffxiv/cos_c1/hou/c1w1/level/c1w1`, `The Sea of Stars - Sinus Ardorum`),
    new FFXIVMapDesc(`ffxiv/cos_c1/hou/c1w2/level/c1w2`, `The Sea of Stars - Phaenna`),
    new FFXIVMapDesc(`ffxiv/cos_c1/hou/c1w3/level/c1w3`, `The Sea of Stars - Oizys`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/fld/u5fa/level/u5fa`, `The Sea of Stars - The Dark Inside (Duty: the Dark Inside)`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/fld/u5fb/level/u5fb`, `The Sea of Stars - The Final Day (Duty: the Final Day)`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/fld/u5f1/level/u5f1`, `The Sea of Stars - Mare Lamentorum`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/fld/u5f2/level/u5f2`, `The Sea of Stars - Ultima Thule`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/evt/u5e1/level/u5e1`, `The Sea of Stars - Beyond the Stars (Duty: Endwalker)`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/evt/u5e3/level/u5e3`, `The Sea of Stars - Elysion`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/dun/u5d2/level/u5d2`, `The Sea of Stars - Smileton (Duty: Smileton)`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/dun/u5d3/level/u5d3`, `The Sea of Stars - The Stigma Dreamscape (Duty: the Stigma Dreamscape)`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/dun/u5d1/level/u5d1`, `The Sea of Stars - The Dead Ends (Duty: the Dead Ends)`),
    new FFXIVMapDesc(`ex4/04_uvs_u5/cnt/u5c1/level/u5c1`, `The Sea of Stars - The Excitatron 6000 (Duty: the Excitatron 6000)`),
    "The World Unsundered",
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r0/level/n5r0`, `The World Unsundered - The Gates of Pandæmonium`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r1/level/n5r1`, `The World Unsundered - The Gates of Pandæmonium (Duty: Asphodelos: The First Circle)`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r3/level/n5r3`, `The World Unsundered - The Fervid Limbo (Duty: Asphodelos: The Third Circle)`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r2/level/n5r2`, `The World Unsundered - The Stagnant Limbo (Duty: Asphodelos: The Second Circle)`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r4/level/n5r4`, `The World Unsundered - The Sanguine Limbo (Duty: Asphodelos: The Fourth Circle)`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r6/level/n5r6`, `The World Unsundered - The Pestilent Purgatory (Duty: Abyssos: The Sixth Circle)`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r7/level/n5r7`, `The World Unsundered - The Hollow Purgatory (Duty: Abyssos: The Seventh Circle)`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r5/level/n5r5`, `The World Unsundered - The Caustic Purgatory (Duty: Abyssos: The Fifth Circle)`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/rad/n5r8/level/n5r8`, `The World Unsundered - Stygian Insenescence Cells (Duty: Abyssos: The Eighth Circle)`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/fld/n5f1/level/n5f1`, `The World Unsundered - Elpis`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/evt/n5e1/level/n5e1`, `The World Unsundered - Propylaion`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/dun/n5d1/level/n5d1`, `The World Unsundered - Ktisis Hyperboreia (Duty: Ktisis Hyperboreia)`),
    new FFXIVMapDesc(`ex4/01_nvt_n5/cnt/n5c1/level/n5c1`, `The World Unsundered - The Shifting Gymnasion Agonon (Duty: the Shifting Gymnasion Agonon)`),
    "Yok Tural",
    new FFXIVMapDesc(`ex5/02_ykt_y6/twn/y6t1/level/y6t1`, `Tuliyollal - Tuliyollal`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/twn/y6ti/level/y6ti`, `Tuliyollal - The For'ard Cabins`),
    new FFXIVMapDesc(`ffxiv/pvp_xx/pvp/y6p1/level/y6p1`, `Wolves' Den Pier - Worqor Chirteh (Duty: Worqor Chirteh (Triumph))`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/fld/y6f1/level/y6f1`, `Yok Tural - Urqopacha`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/fld/y6f2/level/y6f2`, `Yok Tural - Kozama'uka`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/fld/y6f3/level/y6f3`, `Yok Tural - Yak T'el`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/fld/y6fa/level/y6fa`, `Yok Tural - Worqor Lar Dor (Duty: Worqor Lar Dor)`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/evt/y6e1/level/y6e1`, `Yok Tural - Sunperch`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/evt/y6e2/level/y6e2`, `Yok Tural - Skydeep Cenote Inner Chamber`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/evt/y6e5/level/y6e5`, `Yok Tural - Zirgorteh the Open-armed`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/dun/y6d2/level/y6d2`, `Yok Tural - Worqor Zormor (Duty: Worqor Zormor)`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/dun/y6d1/level/y6d1`, `Yok Tural - Ihuykatumu (Duty: Ihuykatumu)`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/dun/y6d3/level/y6d3`, `Yok Tural - The Skydeep Cenote (Duty: the Skydeep Cenote)`),
    new FFXIVMapDesc(`ex5/02_ykt_y6/cnt/y6c1/level/y6c1`, `Yok Tural - Cenote Ja Ja Gural (Duty: Cenote Ja Ja Gural)`),
    "Xak Tural",
    new FFXIVMapDesc(`ex5/01_xkt_x6/twn/x6t1/level/x6t1`, `Solution Nine - Solution Nine`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r2/level/x6r2`, `Xak Tural - Lovely Lovering (Duty: AAC Light-heavyweight M2)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r4/level/x6r4`, `Xak Tural - The Thundering (Duty: AAC Light-heavyweight M4)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r1/level/x6r1`, `Xak Tural - Scratching Ring (Duty: AAC Light-heavyweight M1)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r3/level/x6r3`, `Xak Tural - Blasting Ring (Duty: AAC Light-heavyweight M3)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r7/level/x6r7`, `Xak Tural - Demolition Site (Duty: AAC Cruiserweight M3)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r6/level/x6r6`, `Xak Tural - Rebel Ring (Duty: AAC Cruiserweight M2)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r5/level/x6r5`, `Xak Tural - Groovy Ring (Duty: AAC Cruiserweight M1)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r8/level/x6r8`, `Xak Tural - Hunter's Ring (Duty: AAC Cruiserweight M4)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6r9/level/x6r9`, `Xak Tural - Ring Noir (Duty: AAC Heavyweight M1)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6ra/level/x6ra`, `Xak Tural - The X-Ring (Duty: AAC Heavyweight M2)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6rb/level/x6rb`, `Xak Tural - The Crown (Duty: AAC Heavyweight M3)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/rad/x6rc/level/x6rc`, `Xak Tural - Arcadia (Duty: AAC Heavyweight M4)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6f1/level/x6f1`, `Xak Tural - Shaaloani`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6f2/level/x6f2`, `Xak Tural - Heritage Found`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6fc/level/x6fc`, `Xak Tural - Interphos (Duty: the Minstrel's Ballad: Sphene's Burden)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6fa/level/x6fa`, `Xak Tural - Summit of Everkeep (Duty: Everkeep)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6fd/level/x6fd`, `Xak Tural - Recollection (Duty: Recollection)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6ff/level/x6ff`, `Xak Tural - The Windward Wilds (Duty: the Windward Wilds)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e7/level/x6e7`, `Xak Tural - Zorgor the Boundless (Duty: Bar the Passage)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e2/level/x6e2`, `Xak Tural - The Backroom`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e4/level/x6e4`, `Xak Tural - Tritails Training`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6ef/level/x6ef`, `Xak Tural - Tritails Training`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e1/level/x6e1`, `Xak Tural - Earthen Sky Hideout`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e5/level/x6e5`, `Xak Tural - Greenroom`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e8/level/x6e8`, `Xak Tural - Break Room`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6e9/level/x6e9`, `Xak Tural - Throne Room`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6eb/level/x6eb`, `Xak Tural - Containment Complex 10-29`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d1/level/x6d1`, `Xak Tural - Vanguard (Duty: Vanguard)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d4/level/x6d4`, `Xak Tural - Tender Valley (Duty: Tender Valley)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d2/level/x6d2`, `Xak Tural - Origenics (Duty: Origenics)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d6/level/x6d6`, `Xak Tural - Yuweyawata (Duty: Yuweyawata Field Station)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d7/level/x6d7`, `Xak Tural - The Underkeep (Duty: the Underkeep)`),
    "Unlost World",
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6f3/level/x6f3`, `Unlost World - Living Memory`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6fb/level/x6fb`, `Unlost World - Interphos (Duty: the Interphos)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6fe/level/x6fe`, `Unlost World - The Ageless Necropolis (Duty: the Ageless Necropolis)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/fld/x6fg/level/x6fg`, `Unlost World - Hell on Rails (Duty: Hell on Rails)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6ed/level/x6ed`, `Unlost World - Alexandria Crater`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/evt/x6ee/level/x6ee`, `Unlost World - Bentini Depot`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d3/level/x6d3`, `Unlost World - Alexandria (Duty: Alexandria)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d5/level/x6d5`, `Unlost World - Strayborough (Duty: The Strayborough Deadwalk)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d8/level/x6d8`, `Unlost World - The Meso Terminal (Duty: the Meso Terminal)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/dun/x6d9/level/x6d9`, `Unlost World - Mistwake (Duty: Mistwake)`),
    new FFXIVMapDesc(`ex5/01_xkt_x6/cnt/x6c1/level/x6c1`, `Unlost World - Vault Oneiron (Duty: Vault Oneiron)`),
];

const id = `FinalFantasyXIV`;
const name = "Final Fantasy XIV";

export const sceneGroup: SceneGroup = {
    id, name, sceneDescs,
};